### ISSUE TITLE
strcmp: Invalid BPF_LD_IMM insn

### ISSUE THREAD

**Issue by jesperpedersen** [iovisor/bcc#1132]
I'm still trying to get my first bcc script working, so that I can provide the documentation patch that I promised Sasha.

I have something similar to
```
#!/usr/bin/python
from __future__ import print_function
from bcc import BPF

# load BPF program
b = BPF(text = """
#include <linux/string.h>

struct s_t {
   char a[64];
};

void kprobe__sys_sync(void *ctx) {
    struct s_t s = {0};
    char b[] = "bbbb";

    strcpy(&(s.a[0]), "aaaa");
    bpf_trace_printk("sync() %d\\n", strcmp(&(s.a[0]), b));
};
""")

# header
print("%-18s %s" % ("TIME(s)", "CALL"))

# format output
while 1:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
        print("%-18.9f %s" % (ts, msg))
```
which gives
```
# ./test_strcmp
bpf: Invalid argument
0: (bf) r2 = r10
1: (07) r2 += -59
2: (b7) r1 = 0
3: (73) *(u8 *)(r2 +7) = r1
4: (73) *(u8 *)(r2 +6) = r1
5: (73) *(u8 *)(r2 +5) = r1
6: (73) *(u8 *)(r2 +4) = r1
7: (73) *(u8 *)(r2 +3) = r1
8: (73) *(u8 *)(r2 +1) = r1
9: (73) *(u8 *)(r10 -2) = r1
10: (73) *(u8 *)(r10 -3) = r1
11: (73) *(u8 *)(r10 -4) = r1
12: (73) *(u8 *)(r10 -5) = r1
13: (73) *(u8 *)(r10 -6) = r1
14: (73) *(u8 *)(r10 -7) = r1
15: (73) *(u8 *)(r10 -8) = r1
16: (73) *(u8 *)(r10 -9) = r1
17: (73) *(u8 *)(r10 -10) = r1
18: (73) *(u8 *)(r10 -11) = r1
19: (73) *(u8 *)(r10 -12) = r1
20: (73) *(u8 *)(r10 -13) = r1
21: (73) *(u8 *)(r10 -14) = r1
22: (73) *(u8 *)(r10 -15) = r1
23: (73) *(u8 *)(r10 -16) = r1
24: (73) *(u8 *)(r10 -17) = r1
25: (73) *(u8 *)(r10 -18) = r1
26: (73) *(u8 *)(r10 -19) = r1
27: (73) *(u8 *)(r10 -20) = r1
28: (73) *(u8 *)(r10 -21) = r1
29: (73) *(u8 *)(r10 -22) = r1
30: (73) *(u8 *)(r10 -23) = r1
31: (73) *(u8 *)(r10 -24) = r1
32: (73) *(u8 *)(r10 -25) = r1
33: (73) *(u8 *)(r10 -26) = r1
34: (73) *(u8 *)(r10 -27) = r1
35: (73) *(u8 *)(r10 -28) = r1
36: (73) *(u8 *)(r10 -29) = r1
37: (73) *(u8 *)(r10 -30) = r1
38: (73) *(u8 *)(r10 -31) = r1
39: (73) *(u8 *)(r10 -32) = r1
40: (73) *(u8 *)(r10 -33) = r1
41: (73) *(u8 *)(r10 -34) = r1
42: (73) *(u8 *)(r10 -35) = r1
43: (73) *(u8 *)(r10 -36) = r1
44: (73) *(u8 *)(r10 -37) = r1
45: (73) *(u8 *)(r10 -38) = r1
46: (73) *(u8 *)(r10 -39) = r1
47: (73) *(u8 *)(r10 -40) = r1
48: (73) *(u8 *)(r10 -41) = r1
49: (73) *(u8 *)(r10 -42) = r1
50: (73) *(u8 *)(r10 -43) = r1
51: (73) *(u8 *)(r10 -44) = r1
52: (73) *(u8 *)(r10 -45) = r1
53: (73) *(u8 *)(r10 -46) = r1
54: (73) *(u8 *)(r10 -47) = r1
55: (73) *(u8 *)(r10 -48) = r1
56: (73) *(u8 *)(r10 -49) = r1
57: (73) *(u8 *)(r10 -50) = r1
58: (73) *(u8 *)(r10 -51) = r1
59: (73) *(u8 *)(r10 -57) = r1
60: (73) *(u8 *)(r10 -59) = r1
61: (73) *(u8 *)(r10 -1) = r1
62: (b7) r2 = 1633771873
63: (63) *(u32 *)(r10 -64) = r2
64: (73) *(u8 *)(r10 -60) = r1
65: (73) *(u8 *)(r10 -70) = r1
66: (b7) r1 = 2660
67: (6b) *(u16 *)(r10 -72) = r1
68: (18) r1 = 0x636e7973
70: (7b) *(u64 *)(r10 -80) = r1
71: (bf) r1 = r10
72: (07) r1 += -64
73: (00) r0 = 0x0
invalid BPF_LD_IMM insn

Traceback (most recent call last):
  File "./test_strcmp", line 20, in <module>
    """)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 300, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 901, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kprobe__sys_sync: Invalid argument
```

If the `a` variable is defined inside `kprobe__sys_sync`  then everything is working.

Any hints on the requirements for string operations on struct's would be greatly appreciated

**Comment by goldshtn** [comment]
It's a bit surprising that the strcmp worked at all - this is not a supported operation in BPF programs ... I emulate it in my trace and argdist tools by writing a loop that is guaranteed to be unrollable, so there are no loops.

**Comment by jesperpedersen** [comment]
Ok, thanks for the information.

I guess the question is then how to do a "switch" on a string value from an USDT ala
```
u64 addr = 0;
char val[64] = {0};

bpf_usdt_readarg(1, ctx, &addr);
bpf_probe_read(&val, sizeof(val), (void *)addr);

if (strcmp(&val[0], "First Key") == 0) {

} else if ...
```

**Comment by goldshtn** [comment]
The same way trace and argdist do it. Take a look at the STRCMP implementation in these tools. Basically a loop :)

**Comment by jesperpedersen** [comment]
Thanks for the hint !

I got it working -- though `'u:` based operations need their arguments resolved using the `readarg()` and `probe_read()` functions which isn't supported in `argdist` and `trace` atm.

Defining `static inline` functions for this is probably best.

**Comment by goldshtn** [comment]
I'm pretty sure it is supported e.g. I have an example of tracing Java method calls for a specific method using something like:

`trace 'u::method__entry (STRCMP("gc",arg4) ...'`

**Comment by jesperpedersen** [comment]
OK, `argdist` only supports `$PID` as an alias, which I mainly looked at.

Anyway, got a much clearer idea of how it people should write their script now. I basically just need #1106 to verify my script.

Thanks for your help !

**Comment by ahrens** [comment]
Since BCC doesn't support stcmp(), would it be reasonable to expect the compilation to fail with a message saying that?  For folks using bcc, it isn't easy to go from `invalid BPF_LD_IMM insn` to `strcmp is not a known function`.

A few of my coworkers hit this: @shartse @don-brady

**Comment by palmtenor** [comment]
@ahrens Feel free to added to `bpf_print_hints()` in `libbpf.c`!

**Comment by yonghong-song** [comment]
Previously, probably clang 5.0, llvm do warn/error unknown global functions, so unknown global function `strcmp` will be warned by llvm.

In clang 6.0 and later, this error is gone. The reason is to support regular function calls for bpf programs, and llvm BPF backend does not really track all use/defined global functions and doing this across function boundary may need some work (e.g., some kind of cross-function global state for all defined/referenced global functions, knows what is the last function for the module so that you can emit the error messages.)

At the same time, adding a hint is definitely a good choice. invalid BPF_LD_IMM typically means
referring to a global function or variable which needs relocation. So the hint should let user
check whether they are referencing some global functions or global variables (sometimes including some string constants in readonly sections). llvm bpf backend does try to optimize for string constants by loading into stack first, but may not be always successful.

**Comment by yonghong-song** [comment]
bcc could be improved to handle this as well since it has all the relocation information.

**Comment by ahrens** [comment]
OK, if `invalid BPF_LD_IMM insn` usually means that we've referenced a global that isn't allowed, I can add something to `bpf_print_hints()` to mention that.  It could still be challenging to debug since it doesn't tell you which global it is (or even better, line of code).  I'd like to suggest re-opening this issue to handle improving the error message.

Of course doing https://github.com/iovisor/bcc/issues/691 would also be great, but that would only handle a few specific functions.  I assume you'd get this error when calling any function that's declared but not defined.
