### ISSUE TITLE
TableDesc is noncopyable - why?

### ISSUE THREAD

**Issue by jsedgwick** [iovisor/bcc#1176]
TableDesc has a perfectly functional copy constructor but it is made private and then effectively public again through dup(). Why? This makes it much harder to use in typical RAII fashion.

Is it because the fd is dup()'d under the hood? If so, leaking that out violates basic RAII encapsulation. Copy/move constuctors are there for a reason.

**Comment by drzaeus77** [comment]
Because the TableDesc is meant to map exactly 1:1 to the open bpf maps in the current process. If the TableDesc is copied implicitly, what should the behavior be? Open a new BPF map? How would that get stored in the TableStorage instance?

In the current design, TableDesc is only meant to be constructed once by the compiler and then immediately inserted into a table storage, so there is no need to keep arbitrarily scoped TableDesc on the stack somewhere else. To enforce this usage pattern, it is therefore defined as non-copy-constructible. If you want to use a TableDesc, look it up in the TableStorage instance and keep a local reference or pointer.

**Comment by jsedgwick** [comment]
If you really want 1:1 mappings between TableDescs and bpf maps, at least use shared_ptrs everywhere. Keeping raw pointers or (shudder) references is a recipe for disaster.

That said, I don't understand the need for the 1:1 mappings when TableDesc is POD. Why would it matter if there are multiple copies? Under what circumstances would that be problematic. You can just have copies of TableDescv refer to the same underlying map. See shared_ptrs (or raw, but just no), views over containers, dup'd FDs, and a billion other examples of this pattern.
