### ISSUE TITLE
Can't resolve kernel variables like `page_offset_base`

### ISSUE THREAD

**Issue by i-rinat** [iovisor/bcc#1207]
I can't use `page_to_virt()` macro in a probe function, since it uses particular global variables, which for some reason is being resolved as a function.

Say, if I try to run the following script:
```python
from bcc import BPF

prog = """
#include <linux/mm.h>
int kernel__sys_open(struct pt_regs *ctx) {
    struct page *a = 0;
    void *b = page_to_virt(a);
    bpf_trace_printk("b = %p\\n", b);
    return 0;
}
"""

BPF(text=prog).trace_print()
```
all I get is this error:
```
LLVM ERROR: Program used external function 'page_offset_base' which could not be resolved!
```

`page_offset_base` is an exported symbol (`/arch/x86/mm/kaslr.c`).

**Comment by yonghong-song** [comment]
This is expected through multiple macro expansions:
in linux/mm.h:
#define page_to_virt(x) __va(PFN_PHYS(page_to_pfn(x)))

And bpf program is not able to resolve global variables. This is not
supported now.

The root cause is in arch/x86/include/asm/page_64_types.h:
#ifdef CONFIG_RANDOMIZE_MEMORY
#define __PAGE_OFFSET           page_offset_base
#else
#define __PAGE_OFFSET           __PAGE_OFFSET_BASE
#endif /* CONFIG_RANDOMIZE_MEMORY */

If CONFIG_RANDOMIZE_MEMORY is specified, page_offset_base becomes
configurable so page_to_virt will access some global variables. Unfortunately,
some distro has this config is set. (I checked fc25 only).

Based on my understanding, page_offset_base is only set once during kernel booting.
You can read page_offset_base from kallsyms (page_offset_base is exported).
You have two options:
    . create a map to pass page_offset_base to kernel bpf program and in bpf program,
      you do page_to_virt by using page_offset_base from the map, or
    . you can just get physical in bpf program and send it to user space and let user
      space do the conversion. This may be more efficient.

**Comment by i-rinat** [comment]
Thanks for the tip.

As for the issue, my understanding of what eBPF can do and what can't was wrong. For some reason I was thinking that it is possible call any exported function and access any exported variable.
