### ISSUE TITLE
RSS of BPF_STACK_TRACE programs

### ISSUE THREAD

**Issue by markdrayton** [iovisor/bcc#1291]
Is it expected that increasing the size of a `BPF_STACK_TRACE` map would increase the RSS of the userspace component of a BPF program? E.g., given the following test:

```c
#include <stdio.h>
#include "bpf_common.h"

int main(int argc, char **argv) {
  char text[64];
  sprintf(text, "BPF_STACK_TRACE(test, %d);\n", atoi(argv[1]));
  void *mod = bpf_module_create_c_from_string(text, 4, NULL, 0);
  return !(mod != NULL);
}
```

I see:

```
# env time tests/cc/test_map_size 10 # output omitted
0.08user 0.00system 0:00.09elapsed 96%CPU (0avgtext+0avgdata 39056maxresident)k

# env time tests/cc/test_map_size 100
0.07user 0.00system 0:00.09elapsed 81%CPU (0avgtext+0avgdata 39084maxresident)k

# env time tests/cc/test_map_size 1000
0.07user 0.00system 0:00.07elapsed 97%CPU (0avgtext+0avgdata 40128maxresident)k

# env time tests/cc/test_map_size 10000
0.10user 0.00system 0:00.12elapsed 91%CPU (0avgtext+0avgdata 69552maxresident)k

# env time tests/cc/test_map_size 100000
0.41user 0.10system 0:00.51elapsed 99%CPU (0avgtext+0avgdata 336784maxresident)k
```

So around 3KB per map entry.

A similar test with `BPF_HASH(test, u64, u64, N)` shows ~constant RSS regardless of the map size.

I had assumed that the memory use of the map would be in the kernel, not userspace. Am I misunderstanding how the stack trace maps work, or is this a leak/unreclaimed memory? I tried running this test with jemalloc's heap profiling and the stack that leads to the bulk of these allocations is:

```
llvm::SmallVectorBase::grow_pod(void*, unsigned long, unsigned long)
llvm::raw_svector_ostream::write_impl(char const*, unsigned long)
llvm::raw_ostream::write(unsigned char)
llvm::MCAssembler::writeSectionData(llvm::MCSection const*, llvm::MCAsmLayout const&) const
(anonymous namespace)::ELFObjectWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&)
llvm::MCAssembler::Finish()
llvm::AsmPrinter::doFinalization(llvm::Module&)
llvm::FPPassManager::doFinalization(llvm::Module&)
llvm::legacy::PassManagerImpl::run(llvm::Module&)
llvm::MCJIT::emitObject(llvm::Module*)
llvm::MCJIT::generateCodeForModule(llvm::Module*)
llvm::MCJIT::finalizeObject()
ebpf::BPFModule::finalize()
bpf_module_create_c_from_string
main
```

**Comment by yonghong-song** [comment]
I suspect that if you increase the number of hash table entries, you will see the RSS increase as well.
The memory is allocated in the BPF program. Since the user space owns the file descriptor, so it may count towards to user program RSS. Let me double check this.

Regarding to STACK TRACE per entry count, it should be 127 entries of
struct bpf_stacktrace {
  u64 ip[BPF_MAX_STACK_DEPTH];
};
127 * 8 = 1KB.
Need to investigate why it is 3KB.

**Comment by yonghong-song** [comment]
Looks like the memory overhead is really from userspace. Kernel indeed does some vmalloc, but since it is not touched, it may not count to RSS at all.

Dump the IR, for 1M elements.
===
%struct.test_table_t = type { i32, %struct.bpf_stacktrace, %struct.bpf_stacktrace* (i32*)*, %struct.bpf_stacktrace* (i32*, %struct.bpf_stacktrace*)*, i32 (i32*, %struct.bpf_stacktrace*)*, i32 (i32*, %struct.bpf_stacktrace*)*, i32 (i32*)*, void (i8*, i32)*, void (i32)*, i32 (i8*, i64)*, [100000 x %struct.bpf_stacktrace], i32 }
%struct.bpf_stacktrace = type { [127 x i64] }
@test = local_unnamed_addr global %struct.test_table_t zeroinitializer, section "maps/stacktrace", align 8
====
User space will allocate the zeroinitialized array in user space. It looks like actual RSS is 3X of it so like 3GB.

Tried hash type with 1M elements:
=======
%struct.test_table_t = type { i64, i64, i64* (i64*)*, i64* (i64*, i64*)*, i32 (i64*, i64*)*, i32 (i64*, i64*)*, i32 (i64*)*, void (i8*, i32)*, void (i64)*, i32 (i8*, i64)*, [1000000 x i64], i32 }
@test = local_unnamed_addr global %struct.test_table_t zeroinitializer, section "maps/percpu_hash", align 8
========
The same thing, RSS is roughly 3MB.

Map space allocation in userspace is not needed as kernel allocates the space. Will think of a solution to resolve this.

**Comment by yonghong-song** [comment]
Fixed in master.
