### ISSUE TITLE
Automatically pull in maps

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#137]
Instead of pulling in maps (Python):

```python
stats = b.get_table("stats", c_int, c_ulonglong)
```

The BPF init function should pull these in to the python namespace by default, unless instructed not to (eg, a flag: load_maps = false).

At times this might pull in an unnecessary map, but the value of having them automatically loaded should outweigh that. (If this did become a nuisance, which I doubt, perhaps there could be a BPF_PRIVATE_TABLE() macro in C, for non-auto-loaded maps.)

**Comment by drzaeus77** [comment]
I don't quite understand this request, as in my mind maps are all auto-loaded at constructor time. The call to get_table is just python syntactic sugar.

For background, when get_table is called, it only creates the python wrapper around the table which is already loaded into the kernel (BPF.__init__ time), and as well the fd is already active in the process, just held in an internal C++ data structure. Suppose two calls to get_table were made, then there would be a slight unnecessary overhead of python memory, but the two table handles would return the same entries, since there is no intermediate caching of map data (every [] access translates to a bpf() syscall). Similarly, even if no get_table() is called, the maps are all present in the kernel, since when BPF(text="") was invoked, all of the calls to bpf_create_map were all done. One does not even need to attach the functions anywhere to have the maps active, and there could in theory be a map-only C file with no functions.

Thinking about this problem, I find that there could be an optimization in the python handles, similar to how load_func returns from a python map an already-open handle. However, I think that is not the specific issue you had in mind when opening this request. Am I misunderstanding?

**Comment by brendangregg** [comment]
This isn't that important, but maybe I can explain it better; currently I'm doing this to use a table:

```C
C:
        BPF_TABLE("array", int, u64, dist, 64);
Python:
        dist = b.get_table("dist")
```

The Python line feels a little redundant, like it takes two lines of code to initialize one thing. Can I delete the Python line and have it still work? Eg, for a dist table object in Python to be implicitly created of requiring it to be explicitly declared?

Here's another possibility; bitehist.py currently uses:

```Python
b = BPF(...)
[...]
        dist = b.get_table("dist")
[...]
                        val = dist[c_int(i)].value - last[i]
```

Imagine this instead:

```Python
b = BPF(...)
[...]
                        val = BPF.table("dist")[c_int(i)].value - last[i]
```

This also saves a line, and the get_table() method can be left as-is, as an alternate method for people wanting to explicitly assign tables to Python objects.

**Comment by drzaeus77** [comment]
Yes, this can be done, thanks for clarifying. Currently the getitem api of the BPF object isn't used, what do you think of using that for referring to tables, as in:
```python
b["dist"][c_int(i)].value - list[i]
```

**Comment by drzaeus77** [comment]
Please look into the example syntax in this patch, and let me know if it addresses your cases.

**Comment by brendangregg** [comment]
Yes, looks good, thanks! People can use either b.get_table() or b[] as desired.

I realized my code is lazy and used the global "dist" in a function where it was passed as an arg ("d"). I'll fix...
