### ISSUE TITLE
Issue on tracing a libc function with uprobe

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1371]
Take this simple test program:

```
int main() {
  char str1[4096];
  char str2[4096];
  printf("str1 addr: %p\n", &str1);
  printf("str2 addr: %p\n", &str2);

  auto pid = std::to_string(getpid());
  printf("PID: %s\n", pid.c_str());

  auto path = "/proc/" + pid + "/maps";
  std::ifstream file(path);
  std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
  printf("Memory mapping:\n%s\n", content.c_str());

  while (true) {
    scanf("%s%s", &str1, &str2);
    printf("%d\n", strcmp(str1, str2));
  }
  return 0;
}
```

Compile and run it, I got:
```
qinteng@host:~ {}$ ./test
str1 addr: 0x7ffcce452c20
str2 addr: 0x7ffcce453c20
PID: 1919277
Memory mapping:
00400000-00403000 r-xp 00000000 00:3a 114810809                          /home/qinteng/test
00602000-00603000 r--p 00002000 00:3a 114810809                          /home/qinteng/test
00603000-00604000 rw-p 00003000 00:3a 114810809                          /home/qinteng/test
00604000-00625000 rw-p 00000000 00:00 0                                  [heap]
7f8aa0ef6000-7f8aa10ae000 r-xp 00000000 08:03 62130395                   /usr/lib64/libc-2.17.so
7f8aa10ae000-7f8aa12ae000 ---p 001b8000 08:03 62130395                   /usr/lib64/libc-2.17.so
7f8aa12ae000-7f8aa12b2000 r--p 001b8000 08:03 62130395                   /usr/lib64/libc-2.17.so
7f8aa12b2000-7f8aa12b4000 rw-p 001bc000 08:03 62130395                   /usr/lib64/libc-2.17.so
......
```
Then, I start a uprobe with `trace.py`, and then enter something for the test program, I got:
```
qinteng@host:~ {}$ sudo bcc/tools/trace.py '/usr/lib64/libc-2.17.so:strcmp "%llx %llx",arg1,arg2' -p 1919277 -U
PID    TID    COMM         FUNC             -
1919277 1919277 test         strcmp           7f8aa0f0c551 7f8aa0f06058
```
The address doesn't match what the program sees.

Same thing if we trace `/usr/lib64/libc-2.17.so:strcmp` globally (without PID filter). The argument address doesn't make sense (either 0, 1 or the same across different Processes).

Also, the uprobe with PID filter (i.e. above example) seems only able to be triggered once. No matter how many strings entered with in the test program, no more output in `trace.py` and `/sys/kernel/debug/tracing/uprobe_profile` shows trigger count is always 1.

**Comment by yonghong-song** [comment]
This is not a uprobe issue. The behavior you observed is due to how glibc handling strcmp.

(1). When you call strcmp in user code, it calls strcmp@plt which is an procedure linkage table specific to your process. This table will jump to
       libc shared library. 
(2). When the strcmp is first called, strcmp@plt is first calling a resolver which calls strcmp in glibc:
000000000008b5d0 <strcmp>:
   8b5d0:       48 8b 15 81 48 33 00    mov    0x334881(%rip),%rdx        # 3bfe58 <_DYNAMIC+0x2f8>
   8b5d7:       48 8d 05 12 51 01 00    lea    0x15112(%rip),%rax        # a06f0 <__strcmp_sse2_unaligned>
   8b5de:       f7 82 b0 00 00 00 10    testl  $0x10,0xb0(%rdx)
   8b5e5:       00 00 00
   8b5e8:       75 1a                   jne    8b604 <strcmp+0x34>
   8b5ea:       48 8d 05 0f 44 0c 00    lea    0xc440f(%rip),%rax        # 14fa00 <__GI___strcmp_ssse3>
   8b5f1:       f7 82 80 00 00 00 00    testl  $0x200,0x80(%rdx)
   8b5f8:       02 00 00
   8b5fb:       75 07                   jne    8b604 <strcmp+0x34>
   8b5fd:       48 8d 05 0c 00 00 00    lea    0xc(%rip),%rax        # 8b610 <__GI_strcmp>
   8b604:       c3                      retq
   8b605:       90                      nop
   8b606:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
   8b60d:       00 00 00
essentially, the glibc "strcmp" implementation is a selector for more fine-grained strcmp implementation,
and this will be executed only once. The argument of "str1" and "str2" are not passed to here,
but rather in the resolver function.
(3). Once the implementation selection is done, glibc is able to modify strcmp@plt pointing to
the selected routine and glibc "strcmp" will not be called any more.

The following is the strcmp source code in a recent glibc source repo.
static inline void *
IFUNC_SELECTOR (void)
{
  const struct cpu_features* cpu_features = __get_cpu_features ();

  if (CPU_FEATURES_ARCH_P (cpu_features, Fast_Unaligned_Load))
    return OPTIMIZE (sse2_unaligned);

  if (CPU_FEATURES_CPU_P (cpu_features, SSSE3))
    return OPTIMIZE (ssse3);

  return OPTIMIZE (sse2);
}

Besically, the selection is based on cpu features.

So the easy way is to tries all the "strcmp" variants in the glibc:strcmp function to see which one works and then uprobe that function. In my VM, __strcmp_sse2_unaligned is the one.

**Comment by palmtenor** [comment]
Thank you @yonghong-song for the detailed explanation!
