### ISSUE TITLE
how to use bcc to trace applications inside the container?

### ISSUE THREAD

**Issue by suokun** [iovisor/bcc#1431]
Hi,

I want to trace the application performance inside the container. Here are two options:

1, execute the bcc on the host and trace the applications by pid;
2, execute the bcc inside the application container and trace the applications by pid (Note: this pid is different from the pid seen on the host);

Can anyone tell me the difference? Or what should be the correct ways? Thanks.

**Comment by yonghong-song** [comment]
I would recommend #1 as this moment. Most of bcc tools have PID based filtering mechanism. But PID based filtering won't work if bcc script is executed inside the container. The PID inside the container won't match bpf_get_pid_tgid().

If you do not use pid based filtering, you should be good to run bcc scripts inside the container.

**Comment by goldshtn** [comment]
Note that the bpf() syscall may be explicitly blocked by e.g. seccomp with many container runtimes by default, and that you’d need the container to run with CAP_ADMIN. I think the sensible approach if you need the tools to run in a container, is to have a “sidecar container” that’s running with full privileges, rather than have all containers run with full privileges.

**Comment by goldshtn** [comment]
I believe the question has been answered; feel free to reopen if you have additional related questions.
