### ISSUE TITLE
trace_fields() should quit on KeyboardInterrupt

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#186]
... like trace_readline(). Test program:

vfs_read.py:
```Python
#!/usr/bin/python

from bcc import BPF

# load BPF program
b = BPF(src_file="vfs_read.c")
b.attach_kprobe(event="vfs_read", fn_name="run_read")

# format output
while 1:
	(task, pid, cpu, flags, ts, msg) = b.trace_fields()
	print("got: %s" % msg)
```

vfs_read.c:
```C
# cat vfs_read.c
#include <linux/fs.h>

void run_read(struct pt_regs *ctx, struct file *file)
{
	void *name = 0;

	if (file != NULL && file->f_path.dentry != NULL) {
		bpf_trace_printk("read %s\n", file->f_path.dentry->d_iname);
	} else {
		bpf_trace_printk("was null");
	}
}
```

output:

```
# ./vfs_read.py
[...]
got: read ptmx
got: read ptmx
^CTraceback (most recent call last):
  File "./vfs_read.py", line 11, in <module>
    (task, pid, cpu, flags, ts, msg) = b.trace_fields()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 512, in trace_fields
    return (task, int(pid), int(cpu), flags, float(ts), msg)
KeyboardInterrupt
```

this sometimes happens instead:

```
# ./vfs_read.py
[...]
got: read ptmx
got: read trace_pipe
got: read ptmx
^CTraceback (most recent call last):
  File "./vfs_read.py", line 12, in <module>
    print("got: %s" % msg)
KeyboardInterrupt
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by drzaeus77** [comment]
This is happening because the interpreter is actually busy doing work, not just sitting on the read() call. Meaning, in the first case, python was on the instruction about to return the values to the calling function, and in the second was in the midst of printing to stdout in the vfs_read.py main code.

I don't think anything should (and in the 2nd case cannot) be done in the library to catch these cases, and instead the catch logic should belong in the calling routine. In addition, in the given example, stdout is so busy as to prevent obtaining anything useful, especially since the trace_pipe will have lost many messages.

Let me know if you disagree, and I can move the catch inside trace_fields at least to include a few extra instructions to hide the first type of traceback.
