### ISSUE TITLE
not able to refer socket header

### ISSUE THREAD

**Issue by sch00lb0y** [iovisor/bcc#1935]
```
/virtual/main.c:4:10: fatal error: 'sys/socket.h' file not found
#include <sys/socket.h>
```
but socket.h available in `/usr/include/x86_64-linux-gnu/sys`. I've tried symlink also, it is not working.
can anyone help me with that?

**Comment by ekeih** [comment]
@sch00lb0y Did you find a solution for it? I have the same issue on Ubuntu 16.04.

**Comment by yonghong-song** [comment]
The bpf program cannot access user sys/socket.h program. You need to use kernel-devel packet headers. Could you check whether linux/socket.h works or not?

**Comment by ekeih** [comment]
@yonghong-song Thanks for the feedback. `#include <linux/socket.h>` itself works / does not throw an error. But it does not provide the functionality I expected.

I will give some context to my actual goal, because maybe my approach is completely wrong or there is another better solution.

I have a kprobe attached to `tcp_set_state`. I added comments to describe what I am trying to do.

```
int tcp_set_state(struct pt_regs *ctx, struct sock *sk, int state)
{
    // Only IPv4 is supported, so we can just stop if it is not an IPv4 socket.
    u16 family = sk->__sk_common.skc_family;
    if (family != AF_INET) {
        return 0;
    }

    if (state != TCP_ESTABLISHED && state != TCP_CLOSE) {
      // Stop unless the connection is established or closed. We do not need
      // to continue for any other state of the TCP state machine.
      return 0;
    }

    // At this point I want to figure out if the connection of the socket was initialized as an 
    // outgoing connection or an incoming connection.
    // After hours of searching through Google and man pages I figured out that the
    // following could work.

    int optval;
    socklen_t optlen = sizeof(optval);
    getsockopt(sk, SOL_SOCKET, SO_ACCEPTCONN, &optval, &optlen);

    // But it turns out that `socklen_t` and `getsockopt` are not available. Thats why I tried
    // to `#include <sys/socket.h>`. Using `#include <linux/socket.h>` works as in the import
    // does not fail, but neither  `socklen_t` nor `getsockopt` are available then.
    // I tried this with Ubuntu 16.04 (4.4.x) and 18.04 (4.15.x).

    // I also found `bpf_getsockopt` in `man 7 bpf-helpers` and as far as I understand this
    // should be available with a 4.15 kernel. So I tried to use it by `#include <bcc/helpers.h>`
    // but I still get `unknown func bpf_getsockopt#57` when I try to start my program.

    // ...
}
```

Is it even possible to figure out if it is an incoming or outgoing connection inside of `tcp_set_state`?
I would be very happy for any kind of feedback, even if it is just "you can't to this". :wink:

(I think this question is not really related to the original issue anymore. So if you think that it would be better to join the mailing list or IRC, please let me know :wink:)

**Comment by yonghong-song** [comment]
On Sun, May 5, 2019 at 10:36 AM Max Rosin <notifications@github.com> wrote:

> @yonghong-song <https://github.com/yonghong-song> Thanks for the
> feedback. #include <linux/socket.h> itself works / does not throw an
> error. But it does not provide the functionality I expected.
>
> I will give some context to my actual goal, because maybe my approach is
> completely wrong or there is another better solution.
>
> I have a kprobe attached to tcp_set_state. I added comments to describe
> what I am trying to do.
>
> int tcp_set_state(struct pt_regs *ctx, struct sock *sk, int state)
>
> {
>
>     // Only IPv4 is supported, so we can just stop if it is not an IPv4 socket.
>
>     u16 family = sk->__sk_common.skc_family;
>
>     if (family != AF_INET) {
>
>         return 0;
>
>     }
>
>
>
>     if (state != TCP_ESTABLISHED && state != TCP_CLOSE) {
>
>       // Stop unless the connection is established or closed. We do not need
>
>       // to continue for any other state of the TCP state machine.
>
>       return 0;
>
>     }
>
>
>
>     // At this point I want to figure out if the connection of the socket was initialized as an
>
>     // outgoing connection or an incoming connection.
>
>     // After hours of searching through Google and man pages I figured out that the
>
>     // following could work.
>
>
>
>     int optval;
>
>     socklen_t optlen = sizeof(optval);
>
>     getsockopt(sk, SOL_SOCKET, SO_ACCEPTCONN, &optval, &optlen);
>
>
>
>     // But it turns out that `socklen_t` and `getsockopt` are not available. Thats why I tried
>
>     // to `#include <sys/socket.h>`. Using `#include <linux/socket.h>` works as in the import
>
>     // does not fail, but neither  `socklen_t` nor `getsockopt` are available then.
>
>     // I tried this with Ubuntu 16.04 (4.4.x) and 18.04 (4.15.x).
>
>
Indeed. This won't work. getsockopt is a libc function which cannot be used
in bpf programs.

>
>
>
>
>     // I also found `bpf_getsockopt` in `man 7 bpf-helpers` and as far as I understand this
>
>     // should be available with a 4.15 kernel. So I tried to use it by `#include <bcc/helpers.h>`
>
>     // but I still get `unknown func bpf_getsockopt#57` when I try to start my program.
>
>
>

Could you check uapi bpf.h in your kernel-devel package, which is the
accurate representation whether the kernel

supports or not.

>
>
>     // ...
>
> }
>
>
> Is it even possible to figure out if it is an incoming or outgoing
> connection inside of tcp_set_state?
> I would be very happy for any kind of feedback, even if it is just "you
> can't to this". 😉
>
I am not an expert on this. But I am happy to consult some networking
experts on this and get back to you soon.

**Comment by yonghong-song** [comment]
Looks like there is no such field in `sock` data structure to contain information to differentiate between active and passive connections. One way to do is through maps with sock poiners so you can remember the last tcp state. This is fragile though since hash table may removed an entry for a particular socket. In the future, we have socket local storage which should help.
https://lwn.net/Articles/787194/

Could you describe your use case here? Why do you want to distinguish passive and active connection?

**Comment by ekeih** [comment]
Sorry for my very delayed response! :(

The bcc program I am writing is part of my bachelor thesis where I am trying to collect connection information of (unknown) docker containers (or VMs). So for example I collect the TCP connection information on two servers which both run docker containers which communicate with each other.
What makes it a bit tricky is that the docker daemon uses NAT to provide network connectivity to the containers. So the same TCP connection looks different on both servers:

* Server 1: local: IP:port of container on server 1 <-> remote: IP:port of server 2
* Server 2: local: IP:port of container on server 2 <-> remote: IP:port of server 1

The distinction between passive and active connections would help me to only store the port that was listening for the connection. I do not want to store the randomly chosen port that is used to initiate the connection because it has a negative impact on the cardinality of my metrics. Based on that I would be able figure out which connections are actually the same connections that just look differently because of the NAT.
I think another way to achieve this would be to trace the connect() and accept() calls instead of tcp_set_state(), but it would also need a hash table in the end.

In the end my supervisor and I decided that I will not continue to solve the NAT issue because it is a bit to far outside of the scope of my thesis. But I will definitely add a reference to this discussion to my research because the next person who continues the work based on my thesis will probably want to solve it :)

@yonghong-song I want to thank you for your answers about this topic. You helped me a lot to understand the issues I had with bcc/bpf and I really appreciate your help. Thank you!
