### ISSUE TITLE
Support symbol resolution for short-lived processes

### ISSUE THREAD

**Issue by sandip4n** [iovisor/bcc#2014]
In some cases, symbols in stack traces are not resolved at all. This typically happens when the program being traced exits quickly. This can be observed using the `trace` script as shown below.

```
trace 'p:c:inet_pton' -U
```
when tracing
```
ping -6 -c 1 ::1
```
produces a stack trace like
```
PID     TID     COMM            FUNC             
27444   27444   ping            inet_pton        
        [unknown]
        [unknown]
        [unknown]
```
However, if `ping` keeps running e.g. `ping -6 ::1`, a proper stack trace is seen.
```
PID     TID     COMM            FUNC             
27415   27415   ping            inet_pton        
        __inet_pton+0x0 [libc-2.27.so]
        __GI_getaddrinfo+0x124 [libc-2.27.so]
        [unknown] [ping]
```
This was seen on both `x86_64` and `powerpc64` systems. There are no problems when doing something similar with `perf` though.

**Comment by sandip4n** [comment]
@palmtenor Ah, I see. Thanks for the explanation.
So, can I keep this open for now as more of a feature request?
That is, unless this has been already captured in some other issue.

**Comment by palmtenor** [comment]
Sure, feel free to leave it open. You should change the description to something more generic like "Support symbol resolution on short-lived Processes" or what you find descriptive.

**Comment by sandip4n** [comment]
@palmtenor Done. Thanks.

**Comment by vijunag** [comment]
Part of the problem is that proc entries for the short-lived process disappear. I tried using BUILD_ID in bpf_get_stackid() and it does report the build id. However for a system wide profile, scanning through all the ELF files on the box to match the build-id is too much of a overkill. The patch that added this support here (http://patchwork.ozlabs.org/cover/885955/ ) clearly says the user-space applications will have to maintain mapping between build-id and the corresponding ELF file so that /proc/XXX/smaps doesn't have to be looked up every single time. So, there are two parts to this problem 
1) We definitely need BUILD_ID support so that we don't have to scan through VMAs from smaps
2) The tool has to separately maintain BUILD_ID to ELF mappings. 
I have a patch that has support for BUILD_ID for stackmap and will send it shortly, but if only BPF reported file name instead of BUILD_ID, this problem could've been solved very easily.

**Comment by yonghong-song** [comment]
The idea for the build id is for sysadmin or some super user to build such a database so everybody else can use it to query. If a binary is added by user, the build_id->filename mapping can be
temporarily amended per user base.

For short-lived process, just outputing file name, which you have to have full path to avoid ambiguity, is not enough, since the binary file may be copied/soft linked and may be gone.
For example, binary files are used in containers and shortly after the container is destroyed.

Could you adapt such an approach in your environment?

**Comment by vijunag** [comment]
So what we need is support for BUILD_ID stackmap in bcc. I have the python and the BPF interface part ready, but the back-end parts needs a bit of design thinking. Are you suggesting that user adds the list of libraries/executable to the script and we build a database of build_ids that resolve the offsets to symbols ?

**Comment by yonghong-song** [comment]
> Are you suggesting that user adds the list of libraries/executable to the script and we build a database of build_ids that resolve the offsets to symbols ?

Right. Maybe we can provide some helpers for users to build this database? Or we can have, or assume, another process (local or remote) which is able to take you build _id + offset and gives back to you the symbols? The thinking we do not want to build this database multiple times. The ideal case is to build once and use for many subsequent profiling instances, even from different invocations.

**Comment by vijunag** [comment]
@yonghong-song - I have solved this a bit differently. Having a system-wide process is a good idea, however BCC then will have to deal with the challenges of 1) bringing up/down a daemon 2) RPC mechanism with BCC tools for communication - Although a great idea, requires a new infrastructure. 
I have instead added a new BuildSymbolCache within BCC, where the user can add list of modules that BCC can use for resolving symbols. Probably going forward, the users can only specify the path so that all ELFs under the path can be added to BuildSymCache. 
Added the below patch in trace.py  to report stack_buildid instead of a simple ip pointers. 

diff --git a/tools/trace.py b/tools/trace.py
index e1845da1..768eefc3 100755
--- a/tools/trace.py
+++ b/tools/trace.py
@@ -346,7 +346,7 @@ static inline bool %s(char const *ignored, uintptr_t str) {
                 self.events_name = "%s_events" % self.probe_name
                 self.struct_name = "%s_data_t" % self.probe_name
                 self.stacks_name = "%s_stacks" % self.probe_name
-                stack_table = "BPF_STACK_TRACE(%s, 1024);" % self.stacks_name \
+                stack_table = "BPF_STACK_TRACE_BUILDID(%s, 1024);" % self.stacks_name \
                               if (self.kernel_stack or self.user_stack) else ""
                 data_fields = ""
                 for i, field_type in enumerate(self.types):
@@ -794,4 +794,6 @@ trace -I 'linux/fs_struct.h' 'mntns_install "users = %d", $task->fs->users'
                         exit(0 if sys_exit else 1)

 if __name__ == "__main__":
+        BPF.add_module("/lib/x86_64-linux-gnu/libc.so.6")
+        BPF.add_module("/bin/ping")

Output:
PID     TID     COMM            FUNC
2981    2981    ping            inet_pton
        inet_pton+0x136340 [libc.so.6]
        getaddrinfo+0xfb510 [libc.so.6]
        _init+0x2a08 [ping]
>ping -6 -c 1 ::1

**Comment by yonghong-song** [comment]
This makes sense for the time being. Let us expand the functionality to client/server only if more people starts to use it and feel there is a need. Thanks!

**Comment by vijunag** [comment]
@yonghong-song  - How do we solve the problem here now ? Should we add a new command line arg to use STACK_TRACE_BUILD_ID ? What do you suggest ?

**Comment by yonghong-song** [comment]
I think adding additional options to trace.py makes sense as user can add targeted modules based on what he is tracing. Could you do some study and send out a pull request?

**Comment by sandip4n** [comment]
@vijunag Thanks for fixing this.
