### ISSUE TITLE
want to fetch the current task_struct

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#220]
``` C
                commbyreq.update(&req, (char **)&current->comm);
```

``` Shell
error: couldn't allocate output register for constraint 'r' at line 2148472192
```

If I can't access current directly, then maybe we need a bpf_get_task()?

(This isn't the only time I've wanted something from task_struct.)

**Comment by brendangregg** [comment]
Same error with, say:

```C
        char *commp = (char *)&current->comm;
        bpf_trace_printk("comm: %s\\n", commp);
```

**Comment by drzaeus77** [comment]
It will need to be an official helper, since `current` is a fancy macro that expands into an architecture specific set of asm(). I've hacked around with a very specific use case where I attached to an instruction offset in a function where I knew (by reading the assembly) which register `current` would reside in. That is obviously not portable and not even stable from build to build, so I wouldn't suggest publishing an example that uses that mechanism.

**Comment by 4ast** [comment]
Yeah, current is not accessible directly, so instead of current->comm, please use bpf_get_current_comm() helper. Accessors to other fields can be added as well, but if you want to read *prio* fields, then most likely the answer will be no, since they have complex and kernel specific logic and for analytics it's best not to rely on them. As a workaround, after getting a pid and passing to user space, the process can examine /proc/pid/*

**Comment by goldshtn** [comment]
Now that `bpf_get_current_task` was [added in 4.8](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=606274c5abd8e245add01bc7145a8cbb92b69ba8), it should be exposed from bcc.

**Comment by goldshtn** [comment]
Closing, this is now supported and used by a couple of tools (mountsnoop, cpuunclaimed).
