### ISSUE TITLE
Is there a limit on the loop count in a for loop?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2389]
I have the loop like this:
for (int i = 0; i < 15; i++) {
  ...
  bpf_probe_read(...);
}

It seems any bigger loop limit than 15 will result into a "back-edge from insn .. to .." error, which indicates an unbounded loop?

Is 15 the limit? Or I was doing something wrong elsewhere?

**Comment by palmtenor** [comment]
BPF code does not allow loop (more precisely, jump backwards) since the beginning. The only "loop" you can do is unrolled loop which is probably happened here. When your loop count increase and compiler decided to not unroll the loop, you get the back-edge error.

You can force unroll the loop by using compiler instructions like `#pragma unroll`. But you'll need to take care of the 4096 instructions limit for that.

Proper bounded-loop support is WIP on Kernel side now.

**Comment by yzhao1012** [comment]
Thanks for the quick response, Teng! I really appreciate you and Yonghong's help!

To clarify the 4096 instructions limit, is it applied on the entire program, or just the instructions for a particular probe.

In other words, given the below:
std::string c_text = R"(
....
int probe_write(...) {
  ...
  return 0;
}
...
)";
BPF bpf;
bpf.init(c_text);
bpf.attach_kprobe("__sys_write", "probe_write");

Is the 4096 instructions on the entire c_text, or just the instructions for probe_write() function?

**Comment by palmtenor** [comment]
It's limit of each BPF program you load, regardless of how many function you put in the same file / text.

You can use tail calls if you have good enough Kernel version if you are blocked by the 4096 instructions limit.

**Comment by yzhao1012** [comment]
Thanks Teng! I'll keep tail call as a reference, for now that is not needed.
