### ISSUE TITLE
Use proper Python shebang lines

### ISSUE THREAD

**Issue by cclauss** [iovisor/bcc#2446]
__scripts/py-style-check.sh__ [mandates the use of __#!/usr/bin/python__](https://github.com/iovisor/bcc/blob/master/scripts/py-style-check.sh#L9) but that hardcodes the location of the Python interpreter but on a brew installed Mac or inside a virtualenv, that might not be the desired location.

It would be more standard and flexible to mandate a shebang of __#!/usr/bin/env python__

**Comment by pchaigno** [comment]
Related to #2146.

**Comment by yonghong-song** [comment]
@cclauss The idea is to have /usr/bin/python as the default path and the package installer can have a script to change it to a different appropriate locaiton if needed.

As why use /usr/bin/python instead of `/usr/bin/env python`? This is mostly related what command line is shown (e.g., python vs. opensnoop.py). opensnoop.py is preferred vs. vague python.
https://github.com/iovisor/bcc/issues/2145
