### ISSUE TITLE
Execve can't read args in 4.18 kernel

### ISSUE THREAD

**Issue by cerrus** [iovisor/bcc#2454]
I have been using the sys_execve probe to get the command line arguments and executable name successfully on earlier kernels, and it in fact works with the Python execsnoop example code.  However, if I copy the execsnoop bcc code into the bcc/examples/cc directory and compile it, I don't seem to be reading the arguments.  I see that the cc files are compiled against static vs shared bcc libs, so I'm wondering if that might offer a clue?  Is there a reason the compiled c code version wouldn't have access to the execve arguments?

[ExecSnoop.txt](https://github.com/iovisor/bcc/files/3384409/ExecSnoop.txt)

Python output:
PCOMM            PID    PPID   RET ARGS
vim              97888  8475     0 /usr/bin/vim test.txt

CPP output (argv should contain /usr/bin/vim):
PID: 97910 Comm (bash) argv ()

For reference, I was trying the attached file (altered RandomRead.cc example) with my compiled llvm8 and Bcc version 0.8.0 on RHEL8.

**Comment by zasgar** [comment]
The way the kernel passes arguments to the syscall appears to have changed in version 4.17: https://github.com/torvalds/linux/commit/d5a00528b58cdb2c71206e18bd021e34c4eab878#diff-ee48e9f67ee8420d21b655cfd0eb5d75

Instead of syscall arguments being directly passed through registers, they are instead passed through a single pointer di which has the pt_regs struct. The relevant code is here: 

https://github.com/torvalds/linux/commit/d5a00528b58cdb2c71206e18bd021e34c4eab878#diff-0a0545e0fc76bb70fbb89f9d4638676eL176

As a workaround, we were able to pull out arguments using an offset onto the syscalls pt_regs struct. This is an offset into the ctx->di in the probe function. For example, on the write syscall we can pull out the file descriptor using the following code:

```
int fd;
bpf_probe_read(&fd, sizeof(fd), (void *)ctx->di + offsetof(struct pt_regs, di));
```

There probably needs to be a change made to bcc based on the which version of the kernel is used. Hope this helps.

**Comment by oazizi000** [comment]
Some further digging reveals that BCC already handles the syscall calling convention change:
https://github.com/iovisor/bcc/commit/2da34267fcae4485f4e05a17521214749f6f0edd

In particular, BCC uses CONFIG_ARCH_HAS_SYSCALL_WRAPPER to figure out how which way to interpret the syscall arguments.

However, something is still not quite working for us either. It currently appears that rewriteFuncParam() in b_frontend_action.cc doesn't apply the fix to the right function calls.

Still investigating, but thought I'd share our learnings so far.

**Comment by yonghong-song** [comment]
Thanks. Let us know if you need any help or find a bug and fix and would like to contribute!

**Comment by zasgar** [comment]
@cerrus: If you rename your function "on_sys_execve" to syscall__on_sys_execve it should work because it triggers this part of the code: https://github.com/iovisor/bcc/blob/master/src/cc/frontends/clang/b_frontend_action.cc#L670

This generates the indirect variable assignment that is necessary.

@yonghong-song can you confirm that syscall kprobes always need to be named this way if you intend to capture arguments?

**Comment by yonghong-song** [comment]
@zasgar yes, this is the intention.

**Comment by cerrus** [comment]
@zasgar  Ahhhh, that was the critical detail I missed, thank you.

@yonghong-song did I miss this in the documentation?  I'm more of a user of ebpf and am not familiar with the internals, this might be a good note in the Readme.

Thanks!

**Comment by yonghong-song** [comment]
It is in `reference_guide.md`.

**Comment by cerrus** [comment]
Ah, got it, thanks!
