### ISSUE TITLE
Are probes on syscalls executed concurrently? And what's the concurrency model of probes in general?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2469]
Hi All,

I am curious about the concurrency of syscall probes. We have return probe attached to write() syscall, and the code manipulate BPF maps for internal tracking purpose.

Say I have a return probe on write(). Multiple user space threads are calling write() on the same file descriptor. (Probes for write() calls on different file descriptors,obviously run concurrently)

For probes on write() calls of the same file descriptor, are they running concurrently, or they are actually outside it?

Further, what's the concurrency model of the probes in general? Do they always run in the context of the probed entity, following whatever concurrency model defined by that entity? Is there a general rule?

Thanks in advance!

**Comment by yonghong-song** [comment]
> For probes on write() calls of the same file descriptor, are they running concurrently, or they are actually outside it?
Since different threads could do write() calls at the same time, probes for these concurrent write() calls will be running concurrently.

> Further, what's the concurrency model of the probes in general? Do they always run in the context of the probed entity, following whatever concurrency model defined by that entity? Is there a general rule?

If you are saying "the context of probed entity" is the context (process, softirq) in which traced function (e.g., write()) is executing in the kernel, yes, the probe itself will run in the same context. You can think probe is an extended functionality for the probed function in the same context.
