### ISSUE TITLE
how to fix `no space left on device` 

### ISSUE THREAD

**Issue by tahsinrahman** [iovisor/bcc#2497]
Hi, I'm new to ebpf. I'm trying to load the bpf programs of [sysdig project](https://github.com/draios/sysdig/tree/dev/driver/bpf) using [iovisor/gobpf](https://github.com/iovisor/gobpf) library. It loads some programs successfully, but can't load the [sys_open_x](https://github.com/draios/sysdig/blob/dev/driver/bpf/fillers.h#L132) program. I'm getting the following [error](http://paste.ubuntu.com/p/xJ4WKn2WSz/).

```
panic: error while loading "raw_tracepoint/filler/sys_open_x" (no space left on device)
```

What device is it referring to? I've enough space left on my disk.

How can I fix or debug this types of errors?

Thanks!

**Comment by yonghong-song** [comment]
No familiar with sysdig. Assuming you do not have memory shortage, mostly like this may be you enabled verifier log but verifier log buffer provided too small, so it cannot load.
You can try to remove some non-essential attributes (log, btf, etc.) to see whether the problem is gone or not. If it is gone, you can reversely add back those attributes to find out the reason.

**Comment by tahsinrahman** [comment]
Thanks @yonghong-song, i've manually increased log buffer size, and the programs loaded successfully!
