### ISSUE TITLE
USDT, attach_uprobe in  docker containerised java/nodejs  applications (tools/lib/ustat)

### ISSUE THREAD

**Issue by drandynisbet** [iovisor/bcc#2558]
Hi, I'm trying to develop some code based on the ustat in tools/lib that will be able to trace the execution of managed runtime java/nodejs applications - thiscode currently works fine on a host without executing in a container.  So my first question is does anyone have any simple get me started examples of docker container approaches to bcc/eBPF analysis of applications? 

I've created an ubuntu 19.04 image ...  and also tried running with stock images.
Running my bcc tool on the host (not within the container), and with containerised execution of the application - I can see the creation of a new java/nodejs process using the same techniques as ustat.  I can attach to the sched_switch tracepoint on the host (my code not in ustat) and can read performance counters for microarchitecture events of the PIDS/TIDS belonging to  the java/nodejs application.

ustat is not attaching to USDTs in the containerised java application. I also have a need to do some function hooking using attach_uprobe for internal java/nodejs events that I want to track and these are also not picking up events - so I need to point to the debug symbols somehow as well.

NOTE: all of this works when not using containerised execution. 

I'm aware of Cilium - but have not attempted to dive into it ...  I guess my understanding of containerised execution is missing something obvious ...

Any help/pointers for information and/or explanations would be very helpful.

Thanks, and apologies in advance for any dumbness on my part.,

Andy

**Comment by palmtenor** [comment]
I think `ustat` is attaching to the binary (like `java`) found in host path (like `/usr/bin/java`), which is probably different from the binary in the container. You can verify by checking what binary did `ustat` attached to and if your container process's `/proc/PID/exe` has the same inode

**Comment by drandynisbet** [comment]
Ah yes ... of course the PID is found but the executables and the libjvm.so with the debug symbols for java for example will be in different places (and are different files) host versus container view ....  from the host's point of view my java applications will see
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjvm.so

and the host's mounted view of the container filesystem gives something like ....
/var/lib/docker/aufs/mnt/2a76c6e72580441780fa672f4d41b72ffaaffd0d9351a48eeca0b7a8716d07ed/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

/var/lib/docker/aufs/mnt/2a76c6e72580441780fa672f4d41b72ffaaffd0d9351a48eeca0b7a8716d07ed/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

file /proc/1/exe .... (on the container with bash)
lrwxrwxrwx 1 root root 0 Oct 18 15:46 /proc/1/exe -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

I tried using a (modified) path instead of pid to initialise the USDT but I guess I probably have to enter a path that respects/includes the namespace of the docker container rather than the mounted  view of it on the host ...

**Comment by drandynisbet** [comment]
My issues are strongly related to the problems described in #1366 ...

**Comment by dalehamel** [comment]
@drandynisbet I found this issue while I was looking for dupes while I was about to file my own. I believe we have the same problem.

My investigation shows this functionality was broken by https://github.com/iovisor/bcc/commit/01ee0b61a854e06cb62272ddfbb4eeaf16e9ad7c

I am able to attach to USDT probes in a separate mount namespace in its parent commit:

https://github.com/iovisor/bcc/commit/06e30cca8342aed6a1cd83de65d17945499ab6bb

I was looking into this problem for https://github.com/iovisor/bpftrace/issues/1071, and for my PR to fix it https://github.com/iovisor/bpftrace/pull/1085

In my case, I've tested by running memcached in a docker container, and with the parent commit I can get it to attach:

```
bpftrace -e 'usdt::memcached:command__set { printf("HERE\n")}' -p 3978339
Attaching 1 probe...
^C
```

But not with anything including this commit, as I get this error from bcc:

```
bpftrace -e 'usdt::memcached:command__set { printf("HERE\n")}' -p 3978339
Attaching 1 probe...
cannot attach uprobe, probe entry may not exist
Error attaching probe: usdt:memcached:command__set, to PID: 3978339
```

So that's a smoking gun to me.

**Comment by dalehamel** [comment]
Even weirder, this issue seems to only be present on older kernels (!?).

I am only able to replicate the above problem on a production 4.14 kernel (4.14.65 on google cloud container OS). Locally with a newer kernel (vanilla 5.3.0) I have no issues at all : / 

I wonder if the issue introduced by https://github.com/iovisor/bcc/commit/01ee0b61a854e06cb62272ddfbb4eeaf16e9ad7c is related to some dependency on newer kernel functionality? This would explain why I can't get the regression tests to fail locally, or in CI (which uses 4.15 kernel I think)

**Comment by drandynisbet** [comment]
Hi,
Interesting I will check this out, as I've moved to a newer kernel now too
...

Thanks,
Andy

**Comment by dalehamel** [comment]
@palmtenor I commented more on https://github.com/iovisor/bpftrace/pull/1085 but I think I have this one figured out, assuming it's the same issue.

Basically, newer kernels successfully use perf_event_open to create the probe, older kernels write to debugfs to initialize the uprobe for USDT. #2324 made it so that it always include the full /proc/PID/root as part of the path, but the code already does `setns` to inter the target mount namespace. If the target process is using the host process namespace, it can see the full pid path and this will work, if it is not using the full host process namespace (the usual case for docker containers), the path is invalid and it will fail.

cc @davemarchevsky

**Comment by dalehamel** [comment]
I can think of a few ways to fix this, the simplest would be to just chomp the /proc/PID/root prefix before attaching, as I'm not sure if this path is used / needed elsewhere. The ideal solution would be to simply not prepend this to the path wherever that is happening, assuming that the path can continue to be handled correctly elsewhere.
