### ISSUE TITLE
attach to kprobe sock_hash_delete_elem not working

### ISSUE THREAD

**Issue by dzdx** [iovisor/bcc#2671]
My bcc script is: 
```
#!/usr/bin/python

from bcc import BPF

text = '''
#include <uapi/linux/ptrace.h>
int kprobe__sock_hash_delete_elem(struct pt_regs *ctx)
{
     bpf_trace_printk("delete\\n");
     return 0;
}

int kprobe__sock_hash_update_elem(struct pt_regs *ctx)
{
     bpf_trace_printk("update\\n");
     return 0;
}
'''

b = BPF(text=text)
b.trace_print()
```

I am trying to use ebpf to build a proxy, which uses the two methods `sock_hash_update_elem` and `sock_hash_delete_elem`
but when I trace these two methods using bcc, I find that printk in `sock_hash_update_elem` can output, but it not works in `sock_hash_delete_elem`, I used gdb to determine the kernel address where the code `sock_hash_delete_elem` can be accessed. 
Am I using bcc in the wrong way

kernel version:  4.19.1-041901-generic
ubuntu-18.04.1

**Comment by ariesdevil** [comment]
Get the same result using `bpftrace`. 
Use `bpftrace -e 'kprobe:sock_hash_update_elem { printf("update\n");}'` works well as opposed to using `bpftrace -e 'kprobe:sock_hash_delete_elem { printf("delete\n");}'` show nothing.

**Comment by yonghong-song** [comment]
Maybe you can provide a simple proxy code to show sock_hash_delete_elem() function is actually called?

**Comment by dzdx** [comment]
I tried other kernel function, `sock_map_delete_elem`  also failed to tracing
testing echo-server :  https://github.com/cloudflare/cloudflare-blog/tree/master/2019-02-tcp-splice
bcc code:
```
#!/usr/bin/python

from bcc import BPF

text = '''
#include <uapi/linux/ptrace.h>

int kprobe__sock_map_delete_elem(struct pt_regs *ctx)
{
     bpf_trace_printk("delete\\n");
     return 0;
}

int kprobe__sock_map_update_elem(struct pt_regs *ctx)
{
     bpf_trace_printk("update\\n");
     return 0;
}
'''

b = BPF(text=text)
b.trace_print()
```

gdb can break on the function sock_map_delete_elem
![image](https://user-images.githubusercontent.com/7933207/71766019-3e688c80-2f36-11ea-9e74-b7076993315f.png)

**Comment by yonghong-song** [comment]
I found what is the reason here.
sock_map_update_elem works as seeing the code below.
https://github.com/torvalds/linux/blob/master/kernel/bpf/syscall.c#L999-L1051

sock_map_update_elem is called without `__this_cpu_inc(bpf_prog_active)` which will prevent another bpf program from calling (see kernel/trace/bpf_trace.c).

sock_map_delete_elem does not work as seeing the code below.
https://github.com/torvalds/linux/blob/master/kernel/bpf/syscall.c#L1099-L1106
it is called with `__this_cpu_inc(bpf_prog_active)`.

In general, kprobe/tracepoint bpf internal kernel functions may not work due to 
the above mentioned reasons.

**Comment by dzdx** [comment]
@yonghong-song   thanks for the explanation ！
