### ISSUE TITLE
user symbol translation

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#328]
There should be functions for translating user-level addresses into symbols, similar to the kernel-level ksym() and ksymaddr() functions. These user-level functions likely need to take the PID as an argument.

**Comment by goldshtn** [comment]
I've done a bit of the legwork in [memleak.py](https://github.com/goldshtn/bcc/blob/master/tools/memleak.py). Basically reading `/proc/PID/maps`, calculating offsets, running `objdump -t`, and figuring out which function the address belongs to. I don't know if that's the approach you're going to take though, but it did work for me.

**Comment by brendangregg** [comment]
G'Day Sasha,

Thanks! ... Not sure where else to comment, but I was going to do a memleak.py, and it looks like you're going to beat me to it! ;) So it looks great. I'd consider adding a timestamp to alloc_info_t, so that you can calculate the age of these allocations when printing -- and exclude those younger than a tunable threshold, eg, 500ms. (Not sure how to get the current time from Python for comparison, but anyway.) That'll exclude the usual churn, and show us just the long term survivors, with a higher chance of leaks. Also, if you'd like to push this to bcc (I think you should), please do an example file and man page (copy another that's there). You will have to warn about overhead clearly, since these events are frequent, and have an idea about worst case from testing (testing should include 1-5+ minute runs, BTW, which is what people will want to do to catch slow leaks). I also wrote a CONTRIBUTING-SCRIPTS.md recently in case that's useful, but I already know we want to include this script.

**Comment by goldshtn** [comment]
Brendan, thanks. I'm going to do all of the above. But before anything else, I have to get the tool in a working state -- and it seems that the BPF program deleting entries from the `allocs` map doesn't play well with enumerating it on the Python side. I've opened [an issue for this](https://github.com/iovisor/bcc/issues/350), if you have any pointers for me it would be much appreciated.

**Comment by goldshtn** [comment]
Well, it seems that issue was fixed. I've added a timestamp and an "exclude younger than" option. Will work on figuring out the overhead and documenting this next.

**Comment by brendangregg** [comment]
Ok, thanks; I just did a PR for a tool that also has high overhead (up to 2x: I created a worst case to see what an upper limit might look like), and documented the overheads.

For severe memory leaks, we may not need all the stack traces, but possibly could show a "sample", which could reduce overhead. Eg, one in 10. Actually doing something like "if ((i++ % 10) == 0)" might collide with logical allocation sequences, so I'd have looked at doing a modulus of the timestamp, or of BPF_FUNC_get_prandom_u32. This can be a later addition: a sampling option.

**Comment by goldshtn** [comment]
Well, I've measured and the worst-case overhead (for a program that simply calls `malloc`/`free` repeatedly and does nothing else) is >100x. Obviously the real-world overhead will be lower; I'm working on measuring it. I'm not sure how sampling would work though. Do you mean to sample a call stack for, say, 10% of the allocs, but still record the allocs; or to only record 10% of the allocs? I think the latter would make more sense in terms of eliminating the perf overhead, at the cost of potentially missing some leaks.

P.S. I come from Windows, where there's existing tracing instrumentation (ETW) in the heap (UM) and pool (KM) allocation routines. I've never seen a considerable overhead in a real-world scenario when using these instrumentation points. The overhead would stem from recording all the events for analysis in user-mode, because ETW can't be filtered in-kernel.

**Comment by brendangregg** [comment]
Moving discussion to #354

**Comment by goldshtn** [comment]
@drzaeus77 If you'd like me to, I could migrate the symbol resolution from memleak.py to the BPF module. I'm thinking `usym(pid, addr)` and then use `objdump`, pretty much the same way `find_symbol` is currently implemented.

**Comment by goldshtn** [comment]
I think this can be closed now, in view of #442 being merged.

**Comment by brendangregg** [comment]
yes, thanks!
