### ISSUE TITLE
Memory leaks in libbpf tools

### ISSUE THREAD

**Issue by chenhengqi** [iovisor/bcc#3664]
Some of the libbpf tools have memory leak problems. This is because we have one BPF program but attach it to multiple functions, each attaching creates a new `struct bpf_link *` and these `bpf_link`s are not freed by `xxx_bpf__destroy`.

Take `gethostlatency` as an example:

https://github.com/iovisor/bcc/blob/44fc17fc8ca0a53f37e82aa82a6a000ec28384c4/libbpf-tools/gethostlatency.c#L152-L154

https://github.com/iovisor/bcc/blob/44fc17fc8ca0a53f37e82aa82a6a000ec28384c4/libbpf-tools/gethostlatency.c#L174-L176

The first assignment to `handle_entry` is leaked.

The fix can be done by updating the tool itself. But I wonder whether we should also update bpftool to generate code to cover these use cases.

cc @anakryiko  @davemarchevsky

**Comment by davemarchevsky** [comment]
Thanks for finding this! Looks like this is affecting a few tools. Other tools, like `runqlen` - which needs to create many links as it's working with `perf_events` - are using their own `bpf_link` array for bookkeeping. Regardless, I agree that it's worth considering the more general questions:

* Is supporting >1 link per prog a common enough usecase to make sense to include in skeleton?
* If so, is it possible to add this support to bpftool+libbpf in a reasonable and ideally backwards-compatible way?

I think the answer to 1 is "yes" - otherwise many tracing- and perf-type programs won't be well-supported by the skeleton. After some skimming, I think the answer for 2 is "maybe" - or at least not immediately "no".  In `libbpf.h`, `struct bpf_prog_skeleton`'s `struct bpf_link **link` field could be reinterpreted as an array of `struct bpf_link *` with some "grow when full" behavior. Haven't thought through the implications too much though.

Also not sure if "generated skeleton" would be able to support multi-links in a user-friendly way.

@anakryiko WDYT?
