### ISSUE TITLE
BPF_MAP_TYPE_PERCPU_ARRAY synchronization

### ISSUE THREAD

**Issue by yugeshk** [iovisor/bcc#3696]
I have the following confusion regarding percpu_array  - the bcc documentation [here](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#8-bpf_percpu_array) mentions that updates are not synchronized across the copies of CPUs. However, skimming through the kernel code I see that in the `update_elem` for `percpu_array` there is a loop over all possible CPUs to update the value - [here](https://github.com/torvalds/linux/blob/debe436e77c72fcee804fb867f275e6d31aa999c/kernel/bpf/arraymap.c#L263).

Am I missing something or does the documentation need to be updated?

Thanks!

**Comment by davemarchevsky** [comment]
Your second link is pointing to a loop in `bpf_percpu_array_copy`, but there's a similar loop in `bpf_percpu_array_update` which seems more relevant to the question you're asking. Guessing you meant to ask about the latter function.

Anyways, the API for updating percpu array from userspace differs a bit from the API BPF programs use, but still preserves the "updates are not synchronized" expectation. 

```
	for_each_possible_cpu(cpu) {
		bpf_long_memcpy(per_cpu_ptr(pptr, cpu), value + off, size);
		off += size;
	}
```

The passed in `value` buffer contains a separate value for each cpu, see [`tools/testing/selftests/bpf/test_maps.c`](https://github.com/torvalds/linux/blob/debe436e77c72fcee804fb867f275e6d31aa999c/tools/testing/selftests/bpf/test_maps.c#L417) in kernel source for an example use. The helper called from BPF, `array_map_update_elem`, updates a single `cpu`'s value. 

The semantics probably differ to keep the `BPF_MAP_UPDATE_ELEM` interface simple, since most bpf map types aren't percpu. Most BPF programs use percpu arrays to gather data from the program itself, or as a temporary 'heap' buffer space, and rarely need userspace to populate the percpu array except perhaps with some initial values. If you have a different usecase, though, we'd love to hear about it!
