### ISSUE TITLE
Failed to attach BPF to uprobe

### ISSUE THREAD

**Issue by lanru** [iovisor/bcc#3730]
I use ubuntu20.04, whose kernel version is 5.11.0-41-generic,  when i use memleak, i get 
```
bcc.memleak -t  -p  $(pidof perf_examples)
Attaching to pid 1510059, Ctrl+C to quit.
cannot attach uprobe, Invalid argument
Traceback (most recent call last):
  File "/snap/bcc/159/usr/share/bcc/tools/memleak", line 449, in <module>
    attach_probes("malloc")
  File "/snap/bcc/159/usr/share/bcc/tools/memleak", line 439, in attach_probes
    pid=pid)
  File "/snap/bcc/159/usr/lib/python3/dist-packages/bcc/__init__.py", line 1358, in attach_uprobe
    raise Exception("Failed to attach BPF to uprobe")
Exception: Failed to attach BPF to uprobe
```

 I used dmesg, when i use 'tail -f /sys/kernel/debug/tracing/error_log',  it gives me the info below: 

```
[197806.652880] trace_uprobe: error: Event name is too long
  Command: p:uprobes/p__proc_1510059_root_usr_lib_x86_64_linux_gnu_libc_2_31_so_0x9d260_1510059_bcc_1534830 /proc/1510059/root/usr/lib/x86_64-linux-gnu/libc-2.31.so:0x9d260
```
at last ,i reinstall bcc follow the below article [https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary]

and i resolve the problem

**Comment by yonghong-song** [comment]
Just for your information, the above 'Event name is too long' is caused by the following kernel code,
```
        } else if (len > MAX_EVENT_NAME_LEN) {
                trace_probe_log_err(offset, EVENT_TOO_LONG);
                return -EINVAL;
        }
```
and we have
```
trace/trace.h:#define MAX_EVENT_NAME_LEN        64
```

Obviously the name `p__proc_1510059_root_usr_lib_x86_64_linux_gnu_libc_2_31_so_0x9d260_1510059_bcc_1534830` is too long. I saw the bcc internal has `ev_alias[256]` which is 256 bytes long to hold the event name which may be too big. Need to double check when we hit more than 64 bytes.
