### ISSUE TITLE
total_accesses calculation in cachetop tool

### ISSUE THREAD

**Issue by Cycatz** [iovisor/bcc#4263]
Hi all,
I would like to ask why the [total accesses](https://github.com/iovisor/bcc/blob/b57dbb397cb110433c743685a7d1eb1fb9c3b1f9/tools/cachetop.py#L107) is defined as the times of entering `mark_page_accessed` plus `mark_buffer_dirty` functions?

From my point of view, doesn't the times entering `mark_buffer_dirty` function include the times entering `mark_page_accessed`, that is, doesn't they overlap?

Best Regards,
Fan

**Comment by brendangregg** [comment]
The origin of the algorithm:

https://github.com/brendangregg/perf-tools/blob/master/fs/cachestat
https://www.brendangregg.com/blog/2014-12-31/linux-page-cache-hit-ratio.html

Note: it's a **proof of concept**, for **Linux 3.13**, and was written for **Ftrace function profiling** and not eBPF. I put those details in the header of the tool, but they have not been copied over to these ports.

Taking a step back: The real problem here is that people are porting tools without porting the warnings and comments. That's the root of the problem here. Someone needs to add back the warnings.

I explain the overlap in the blog post, but you have to think about it with that missing context: This was written for Ftrace, on Linux 3.13, as a proof of concept. Ftrace could only count function calls. If I were to write it for eBPF, it may be totally different (or not -- I don't know -- I have never tried).

Taking an even bigger step back: It's a proof of concept. These are such critical metrics that you shouldn't need a tracing tool to measure them. They should be in /proc. I said this to the mm folk in my LSFMM keynote in Puerto Rico 2019, they replied that it's actually quick tricky to do.

So many people care about cachestat working that I think it's achieved its goal as a proof of concept. It's proven people want it. So I think the right way to fix it is not to worry about how cachestat works or doesn't (given its origin and limitations) but instead the best approach would be to abandon it and add the metrics to /proc, directly in the kernel, using whatever C code makes sense. Then we can make cachestat an awk script that reads /proc.

**Comment by Cycatz** [comment]
@brendangregg  Thank you so much for the reply! 
> I explain the overlap in the blog post, but you have to think about it with that missing context: This was written for Ftrace, on Linux 3.13, as a proof of concept. Ftrace could only count function calls. If I were to write it for eBPF, it may be totally different (or not -- I don't know -- I have never tried).

So that is due to the functional limitation of *ftrace*, which provides only function counts, making us estimate the cache statistics using with merely these counter variables.

> So many people care about cachestat working that I think it's achieved its goal as a proof of concept. It's proven people want it. So I think the right way to fix it is not to worry about how cachestat works or doesn't (given its origin and limitations) but instead the best approach would be to abandon it and add the metrics to /proc, directly in the kernel, using whatever C code makes sense. Then we can make cachestat an awk script that reads /proc.

I totally agree that the best approach to collect the cache information is adding code directly in the kernel, instead of using tracing results.

**Comment by yonghong-song** [comment]
There is an upstream proposal to get cachestat for a particular file:
   https://marc.info/?l=linux-mm&m=167026227700962&w=2
by introducing a new cachestat syscall.

This doesn't provide system-level cachestat information. If you are interested, pls take a look. You can comment in this thread or directly in upstream thread.
