### ISSUE TITLE
invalid argument: unknown func bpf_d_path (Is there a function that can replace this function?)

### ISSUE THREAD

**Issue by XiaoNuoZ** [iovisor/bcc#4291]
Hi there,

I want to get the filename through the kernel's vfs_read() function, I want it to start from the root directory, I got this error using bpf_d_path.

I'm just starting to learn ebpf, so maybe I'm using it wrong?

Is there an easier way, I want to pass a file, return a root directory address, and then put this address into the event to send.

Can you help me?

Thanks!

code:
```
	struct file *fs = (struct file *)PT_REGS_PARM1(ctx);
	char buf[100];

	bpf_d_path(&fs->f_path,buf,sizeof(buf));
```

error:
`loading objects: field TraceVfsRead: program trace_vfs_read: load program: invalid argument: unknown func bpf_d_path#147 (50 line(s) omitted)`

**Comment by GermanCoding** [comment]
Have you found a solution? Having a similar issue.

**Comment by qjerome** [comment]
Hi,
I am playing with eBPF since a while now (but I am not an expert) so what I will say is may be wrong !
According to the presentation https://lpc.events/event/7/contributions/672/attachments/541/960/dpath.pdf bpf_d_path is not implemented for all the probes (so it is probably not for the type of probe you are using). On my side I could figure out that it does not work neither for **k(ret)probes** nor for **tracepoint** kind of probes.  One possible way is to parse the path manually, as done here: https://github.com/redcanaryco/redcanary-ebpf-sensor/blob/main/src/process/path.h

**Comment by GermanCoding** [comment]
bpf_d_path is supported in Linux kernel v5.10 and up (see [the commit](https://github.com/torvalds/linux/commit/6e22ab9da79343532cd3cde39df25e5a5478c692) tags).

Even with supported kernels, `bpf_d_path` can only be called in very specific situations - only for BTF id's part of [the allowlist](https://github.com/torvalds/linux/blob/ec35307e18ba8174e2a3f701956059f6a36f22fb/kernel/trace/bpf_trace.c#L924) or supported programs. Currently, these are primarily raw tracepoints and sleepable BPF LSM programs.

**Comment by vpidatala94** [comment]
Thanks a lot for your comments, got much needed clarity: based on it, I tested the function, but still getting: ideally this should work right?
;
19: (07) r2 += -272
; bpf_d_path(&curr_path, buf, sizeof(buf));
20: (b7) r3 = 256
21: (85) call bpf_d_path#147
unknown func bpf_d_path#147
processed 20 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 0
-- END PROG LOAD LOG --


 on a tracepoint as follows: SEC("tp/syscalls/sys_enter_write")
int handle_tp(void *ctx)
{
        int pid = bpf_get_current_pid_tgid() >> 32;

        if (pid != my_pid)
                return 0;

        bpf_printk("BPF triggered from PID %d.\n", pid);


        struct path curr_path;
        char buf[256];
        struct task_struct *current = (void *)bpf_get_current_task();
        if (current == NULL) return 0;
        bool is_root = true;
        curr_path.mnt = 0;
        curr_path.dentry = 0;
        bpf_d_path(&curr_path, buf, sizeof(buf));

        return 0;
}

**Comment by qjerome** [comment]
No it should not work, because sys_enter_write is not part of the allow list. Pick a function in the allow list, make sure it is called and create a fentry/kprobe/lsm hook (as allow list does not seems to contain functions to tracepoint). To be honest I managed to make the eBPF prog pass the verifier but I did not find any usefulness of using this function as the allow list is super restrictive. The only way (I know) to get path resolution from almost every probe is to implement a path parsing function by yourself, or pick one in existing projects.

-------- Message d'origine --------

**Comment by vpidatala94** [comment]
Oh I see!, thank you see I see the code now, this is super restrictive! :(, can you point me to a piece of code that you took reference from for parsing paths?

**Comment by vpidatala94** [comment]
Skipping bpf_d_path and using 

SEC("kprobe/dentry_close")
int BPF_KPROBE(dentry_close)
{
    struct dentry *de = NULL;
    struct qstr dn = {};
    struct path curr_pwd = {};
    char buf[256];
    struct dentry* curr_dentry;
    struct task_struct *curr = (struct task_struct *)bpf_get_current_task();
    const unsigned char* name = NULL;
    unsigned char* dpath = NULL;
    char* (*func)(struct dentry*, char*, int);
    char *pstr = NULL;
    if (curr == NULL || BPF_CORE_READ(curr,fs) == NULL) return 0;
    curr_dentry = BPF_CORE_READ(curr, fs, root.dentry);
    name = BPF_CORE_READ(curr,fs,root.dentry,d_name.name);
    func = BPF_CORE_READ(curr,fs,pwd.dentry,d_op, d_dname);
    if (func == NULL) return 0;
    pstr = func(curr_dentry, buf, 256);
    bpf_probe_read_kernel_str(buf, sizeof(buf), pstr);
    bpf_printk("INET_RECVMSG 1 : %s", pstr);
    return 0;
}

//This is not working I am getting an error as  below, probably because BPF is not able to do address resolution, any workarounds I am basically trying to call dentry_op function d_dname
client:./kprobe
libbpf: prog 'inet_recvmsg_exit': BPF program load failed: Invalid argument
libbpf: prog 'inet_recvmsg_exit': -- BEGIN PROG LOAD LOG --
unknown opcode 8d
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: prog 'inet_recvmsg_exit': failed to load: -22
libbpf: failed to load object 'kprobe_bpf'
libbpf: failed to load BPF skeleton 'kprobe_bpf': -22
Failed to open BPF skeleton
client:

**Comment by vpidatala94** [comment]
Found this post for reference: https://github.com/iovisor/bcc/issues/237

**Comment by qjerome** [comment]
Cannot help much with your last issue, sorry ! I never had such a problem.
You can find a path resolution implementation there : https://github.com/redcanaryco/redcanary-ebpf-sensor/blob/main/src/process/path.h

It is implemented using tail calls but you can easily translate the code without tail calls (i.e. only using loops). You could maybe use bpf_loops function if you don't target too old kernels.
-------- Message d'origine --------

**Comment by antisecc** [comment]
eBPF ISA have limited set of instructions so, I am assuming when you compile your code it is compiling it for x86-64 machine code instruction, so the program is not an actual BPF bytecode. Thus getting `unknown opcode 8d`

So in my case what I did was to verify that my compile instruction have `-target bpf`

And verify BPF header file works for my kernel or not

**Comment by KnightChaser** [comment]
> Hi, I am playing with eBPF since a while now (but I am not an expert) so what I will say is may be wrong ! According to the presentation https://lpc.events/event/7/contributions/672/attachments/541/960/dpath.pdf bpf_d_path is not implemented for all the probes (so it is probably not for the type of probe you are using). On my side I could figure out that it does not work neither for **k(ret)probes** nor for **tracepoint** kind of probes. One possible way is to parse the path manually, as done here: https://github.com/redcanaryco/redcanary-ebpf-sensor/blob/main/src/process/path.h

Hi, I may be too late, but the link you suggested(https://github.com/redcanaryco/redcanary-ebpf-sensor/blob/main/src/process/path.h) seems to be expired, because I can't find the content of the given URL. 

I'm currently also experiencing similar issues, such as below(`bpf_d_path` helper function unavailability issue), so I couldn't help but ask questions.
```
program on_vfs_unlink: load program: invalid argument: helper call is not allowed in probe (30 line(s) omitted)
```
