### ISSUE TITLE
undefined symbol: bpf_module_rw_engine_enabled

### ISSUE THREAD

**Issue by lucky0218** [iovisor/bcc#4542]

**Comment by lucky0218** [comment]
an error occurred when 'from bcc import BPF' in python

**Comment by arjuntemura** [comment]
I encountered the same error with Ubuntu 18.04 and python 3.8. 
How can we resolve this?

**Comment by ShawnZhong** [comment]
It works for my by reinstalling BCC: `sudo make install` under `build`

**Comment by matthew-olson-intel** [comment]
This issue is caused by trying to use `/usr/lib/x86_64-linux-gnu/libbcc.so` provided by the Ubuntu 18.04 package (which, I think, is `libbpfcc`, if I remember correctly).

The fix here is to use *either* the Ubuntu packages (e.g. `libbpfcc`, `bpfcc-tools`, `libbpfcc-dev`, etc.), *or* the from-source BCC version (so, `sudo make install` after uninstalling the Ubuntu packages).

**Comment by brendangregg** [comment]
Thanks @matthew-olson-intel for checking, closing.
