### ISSUE TITLE
[RFC] Alternate binding implementations

### ISSUE THREAD

**Issue by vmg** [iovisor/bcc#455]
From the BCC readme:

> In the future, more bindings besides python will likely be supported. Feel free to add support for the language of your choice and send a pull request!

This is very cool. Let's say that hypothetically GitHub (my employer) had a mostly feature complete `libbcc` toolkit written in LuaJIT, with very interesting performance characteristics because it's able to JIT-compile the C types for the FFI interface to the probes. We may also (hypothetically) have ported many of the existing examples and tools to the new toolkit as examples.

Would you folks be interested on keeping this toolkit "in-tree" (i.e. just like the Python wrapper is kept in this repository), or shall we rather open-source it eventually on its own repository?

**Comment by drzaeus77** [comment]
It could make sense to have in-tree, but really it's about whichever makes the code look cleaner. For instance, I've been working on a Go-based tool that uses bcc (iovisor/iomodules), and that links against the C api that libbcc exposes, but obviously isn't in this same repo. The decision to split that out came not because of a desire to split the repos, but because the use case is different...it's not just language bindings but a completely orthogonal tool, which will have a life of its own.

So, whichever you think makes sense: language bindings in this repo or a separate tool, perhaps in a new repo under iovisor/. Or maybe a bit of both?

**Comment by vmg** [comment]
Thanks for the context!

> The decision to split that out came not because of a desire to split the repos, but because the use case is different...it's not just language bindings but a completely orthogonal tool, which will have a life of its own.

In our case the tool is so far (faster) bindings to libbcc, so I'm going to open a PR and we can see how it looks. I agree obviously agree that complex tools using those bindings should be on a separate repository. :)

**Comment by 4ast** [comment]
we had an agreement to stabilize c++/c api of libbcc.so eventually, but today we're far from it. So at the moment any python/go/lua bindings on top of libbcc should really be part of bcc repo, otherwise they will keep breaking. If lua-based tools are going to be similar to python based then makes sense for them to live in tools directory as well, so both can be improved/bugfixed together. Even more complex stuff if it's building on top of libbcc.so can incubate here too. Just to be exposed to more eyes of the community. Small self-managed repos typically has less oversight, less codereviews, less critical feedback.

**Comment by vmg** [comment]
This shipped and is being worked on. Closing this RFC!
