### ISSUE TITLE
offcputime user/kernel stack order

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#559]
```
# ./offcputime.py -p 21077
Tracing off-CPU time (us) of PID 21077 by user + kernel stack... Hit Ctrl-C to end.
^C
    00007f4ff2a4f810 __read
    000000000040866f read_token
    000000000040816d yylex
    000000000040580e yyparse
    000000000040546b parse_command
    000000000040553c read_command
    0000000000405270 reader_loop
    00000000004038e7 main
    00007f4ff2985ec5 __libc_start_main
    ffffffff810a16d1 finish_task_switch
    ffffffff817b3255 schedule
    ffffffff817b5d1b schedule_timeout
    ffffffff810bc0f3 wait_woken
    ffffffff814b6308 n_tty_read
    ffffffff814b0df2 tty_read
    ffffffff81205168 __vfs_read
    ffffffff81205fcf vfs_read
    ffffffff812073c6 sys_read
    ffffffff817b6d76 entry_SYSCALL_64_fastpath
    -                bash (21077)
        124267
```

Note that the output begins with user, then shows kernel. I think it should be the other way around, kernel first, then user, to preserve the logical code flow from the bottom of the stack to the top. You always begin with "main" at the bottom, then work up, and sometimes enter the kernel.

Same with folded:

```
# ./offcputime.py -fp 21077
^Cbash;entry_SYSCALL_64_fastpath;sys_read;vfs_read;__vfs_read;tty_read;n_tty_read;wait_woken;schedule_timeout;schedule;__libc_start_main;main;reader_loop;read_command;parse_command;yyparse;yylex;read_token 239532
```

Oops, another bug (maybe mine): note that the folded output is missing "__read" and "finish_task_switch" -- must be an off-by-one bug in the loops.

I'd also add an option to insert a delimiter frame, "-", which is supported by flamegraph.pl (it colors it grey). Eg, as -d:

```
# ./offcputime.py -d -p 21077
Tracing off-CPU time (us) of PID 21077 by user + kernel stack... Hit Ctrl-C to end.
^C
    ffffffff810a16d1 finish_task_switch
    ffffffff817b3255 schedule
    ffffffff817b5d1b schedule_timeout
    ffffffff810bc0f3 wait_woken
    ffffffff814b6308 n_tty_read
    ffffffff814b0df2 tty_read
    ffffffff81205168 __vfs_read
    ffffffff81205fcf vfs_read
    ffffffff812073c6 sys_read
    ffffffff817b6d76 entry_SYSCALL_64_fastpath
    - -
    00007f4ff2a4f810 __read
    000000000040866f read_token
    000000000040816d yylex
    000000000040580e yyparse
    000000000040546b parse_command
    000000000040553c read_command
    0000000000405270 reader_loop
    00000000004038e7 main
    00007f4ff2985ec5 __libc_start_main
    -                bash (21077)
        124267

# ./offcputime.py -d -fp 21077
^Cbash;__libc_start_main;main;reader_loop;read_command;parse_command;yyparse;yylex;read_token;-;entry_SYSCALL_64_fastpath;sys_read;vfs_read;__vfs_read;tty_read;n_tty_read;wait_woken;schedule_timeout;schedule 239532
```

/CC @evverx

**Comment by evverx** [comment]
> note that the folded output is missing "__read" and "finish_task_switch" -- must be an off-by-one bug in the loops

Indeed. See #561

**Comment by evverx** [comment]
>  I think it should be the other way around, kernel first, then user, to preserve the logical code flow from the bottom of the stack to the top.

@brendangregg , I like this idea!

Well, user stacks were introduced by @abirchall (1f202e7b489). @abirchall , what do you think?

**Comment by evverx** [comment]
Anyway, the fix is trivial. Please have a look #562

**Comment by abirchall** [comment]
This makes sense to me, we should fix this.

As an aside, how should we handle cases where user space is entered from kernel space? Consider a stack trace capturing user space code that is executed due to a tracepoint / kprobe in a PF_KTHREAD. @4ast brought this up to me as an example of why we may want to call get_stackid to populate user_stack_id even for PF_KTHREAD's.

In a case like this I would assume the stack trace would read as follows:
<user_space>
<kernel_space>

Even more complicated would be user space calling into kernel space which calls user space for a tracepoint / kprobe:
<user_space> (stack from tracepoint / kprobe user space code)
<kernel_space> (stack from kernel space)
<user_space> (stack from main)

Thoughts?

**Comment by abirchall** [comment]
Using an option to add a delimiter between the user / kernel space stacks sounds good to me. Originally I added it by default in my original implementation but removed it before uploading the PR because of #545. We'll need to use a delimiter when showing the waking stack trace / chain of waking stacks; at which point we may not want to respect the option to add a delimiter between the user / kernel stacks. But I can take care of all of this when I get around to #545.

**Comment by brendangregg** [comment]
I can't think of an example right now of when a PF_KTHREAD would call into, and execute, user code. I'm sure a PF_KTHREAD can call tracepoints or kprobes, and we could try to fetch the user-level stack, but I'd assume the user-level stack in that case would be NULL.

As for delimiters, I think its usage in this tool is ok. For multiple stacks, then yes, we may want two modes:

- -d, --delimit-modes (user- and kernel-mode, as with offcputime)
- -D, --delimit-threads

Of course, one could also use both for those tools: -dD, to delimit everything.

**Comment by 4ast** [comment]
when asked for user stack, the get_stack_id() will do:
if  (current->mm) regs = task_pt_regs(current);
and walk it, so in irq or in any kprobe/tracepoint triggered in the call chain of irq,
user mode stack could be meaningful, but unlikely interesting for offcputime tool.
Will be useful for https://github.com/iovisor/bcc/issues/330 and sampling.

**Comment by brendangregg** [comment]
Oh, ok, sampling. (Isn't that not PF_KTHREAD though?). But for sampling I'd think the kernel interrupt stack should be tossed out -- it's the implementation of sampling, not the target of sampling.

**Comment by brendangregg** [comment]
... the sampling case also isn't an example of the kernel beginning to execute new user code. If the kernel has interrupted already-running user, I think that's a pretty normal case where the kernel stack goes on top. We've entered the kernel via an interrupt, instead of a syscall.

Yes, it can happen at random places, and profiling a CPU & network heavy application ends up with a user-mode flame graph covered with kernel-stack "hair". But that's how it currently works with perf_events profiling etc.

**Comment by 4ast** [comment]
the irq stack of 'implementation' shouldn't be seen, since kernel remembers pt_regs at the time of kprobe/tracepoint and eventually right at sampling irq, so implementation artifacts should be tossed out automatically. That's why 'ctx' is passed into bpf_get_stack_id() otherwise we'd see bpf+kprobe handlers.
Yes. It's exactly the same as perf_events, since code is shared :)
