### ISSUE TITLE
The overhead of bpf_ktime_get_ns()

### ISSUE THREAD

**Issue by mattwang24** [iovisor/bcc#578]
Hi all,

when I use bcc to trace latency of kernel codes, bpf_ktime_get_ns() will provide nanosecond level granularity information for me. However, I am concerned about the overhead of bpf_ktime_get_ns(). I read the source of bpf_ktime_get_ns() and it will finally get time from clocksource CLOCK_MONOTONIC.

Here is a tool to measure the overhead of different clocksource in Linux. 
https://github.com/btorpey/clocks

If the read of clocksource CLOCK_MONOTONIC has too high overhead, how to change to read other clocksources, e.g. rdtsc. Thanks.

Matt

**Comment by 4ast** [comment]
comparing user space clocks is not representative of the same clocks in kernel

**Comment by mattwang123** [comment]
Hi 4ast, thank you for your reply. I felt a little confused about your answer and can explain more detailed about that. 

http://btorpey.github.io/blog/2014/02/18/clock-sources-in-linux/
Two factors will influence the accurate of measuring latency in the kernel: 1, the granularity of the clocksource(e.g. ns, us, etc) and the cost of read from the clocksource. The cost of getting time from different clocksources are different.

Very appreciated for your answer. :)

**Comment by 4ast** [comment]
so the accuracy is the concern or performance? If latter, please measure the actual cost of ktime_get_ns vs rdtsc and describe the application where the difference would matter

**Comment by mattwang123** [comment]
The accuracy is the concern.

For example, if the user wants to measure the time spent from function A to function B, read t1 at function A and t2 from function B, then |t2-t1| is the time spent from function A to function B.

However, if the "read" time itself has too much overhead, the |t2-t1| is not accurate any more(compared to nanosecond precision), especially for high speed network. Read from different clocksources would have relationship with the overhead of read, as the above link illustrates. However, the bcc only provides bpf_ktime_get_ns(get time from CLOCK_MONOTONIC), but not options from other clocksources. Sometimes the CLOCK_MONOTONIC is not the best option in some cases, for example, in my VMs CLOCK_MONOTONIC has high overhead compared to rdtsc.

Right now, I cannot measure the cost of bpf_ktime_get_ns, but the overhead of CLOCK_MONOTONIC is a subset of overhead of bpf_ktime_get_ns. Looking forward for your reply. :)

**Comment by mattwang123** [comment]
One example is 
https://github.com/iovisor/bcc/blob/master/examples/tracing/disksnoop.c
which traces block device I/O latency. 

bpf_ktime_get_ns() gets time from the beginning and end of each disk request. The overhead of CLOCK_MONOTONIC is about 52ns while the overhead of rdtsc is 26ns. In some VMs of my university, the overhead of CLOCK_MONOTONIC could be over 1000ns in some cases.

Also, CLOCK_MONOTONIC stops when the system is suspended. However, the constant_tsc and nonstop_tsc in modern processors guarantee that the TSC increases in a constant rate even the machine enters energy-saving mode. 

The bpf_ktime_get_ns(based on CLOCK_MONOTONIC) works in most cases. What I just wonder is can bcc(or we can say bpf) support more clocksources(e.g. based on tsc) for users? Thanks.

**Comment by 4ast** [comment]
> The overhead of CLOCK_MONOTONIC is about 52ns while the overhead of rdtsc is 26ns

pls show the code that measures it

**Comment by mattwang24** [comment]
Hi 4ast, 

I just use this program: https://github.com/btorpey/clocks

Here is the result in one of VM:
ClockBench.cpp
Method	                                      samples	    min	    max	    avg	 median	  stdev
CLOCK_REALTIME	                   255	  27.00	  37.00	  34.43	  32.00	   2.67
CLOCK_REALTIME_COARSE	   255	   0.00	   0.00	   0.00	   0.00	   0.00
CLOCK_MONOTONIC	                   255	  28.00	  37.00	  34.98	  32.50	   2.50
CLOCK_MONOTONIC_RAW	           255	  69.00	  81.00	  76.24	  75.00	   2.39
CLOCK_MONOTONIC_COARSE	   255	   0.00	   0.00	   0.00	   0.00	   0.00
cpuid+rdtsc	                                   255	 739.00	 761.00	 742.80	 750.00	   4.12
rdtscp	                                           255	   8.00	  14.00	  10.55	  11.00	   2.08
rdtsc	                                                   255	   6.00	  11.00	   7.66	   8.50	   1.88
Using CPU frequency = 2.800000

**Comment by mattwang24** [comment]
Hi 4ast,

I just use this program: https://github.com/btorpey/clocks

Here is the result in one of VM:

![deepinscrot-2133](https://cloud.githubusercontent.com/assets/15696292/16254583/3c11962e-37f6-11e6-9f70-4488da9ac2fc.png)

**Comment by 4ast** [comment]
> I just use this program: https://github.com/btorpey/clocks

once again:
comparing user space clocks is not representative of the same clocks in kernel.
write kernel module that measures both.

**Comment by vmg** [comment]
@mattwang24: To expand on what 4ast's point, the clock benchmarks you're pointing to are not really relevant because they are userland benchmarks. This means that they must access the clock source either via a syscall+context switch, or through a vDSO. The benchmark is hence mostly dominated by the overhead of accessing the clock source, and not by the clock source itself.

The function you're worried about, `bpf_ktime_get_ns`, is always called from inside your BPF probe and these probes _run in kernel space_ (thanks to the magic of statically verified BPF bytecode). There is no overhead there to access the clock source and no context switches or indirection.

With these considerations in mind, I believe it makes sense sticking to the `CLOCK_MONOTONIC` source, as it is the most accurate for monotonic ticks and the performance difference between other sources, once you don't factor in access time, is negligible.

I would be very surprised if you could benchmark a use case where the monotonic source is _too slow_ for profiling, and yet a more coarse time source is _accurate enough_ to give meaningful results. The faster the clock source, the more coarse it needs to be, and with a coarse timer at high throughput, you'll essentially be profiling noise.

I'd love to be proven wrong about this, so feel free to whip up your own clock benchmark. But remember it needs to run on the kernel!

**Comment by brendangregg** [comment]
Closing issue (ticket tidy). Please reopen if this is still deemed an issue. The clock benchmarks are useful for a certain purpose, but as has been said, we're measuring from kernel context here, so things are different.
