### ISSUE TITLE
Migrate Python tools to bcc USDT and procutils support

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#592]
There are some Python tools (notably `trace` and `argdist`) that still use the `USDTReader` and `ProcUtils` interfaces for things that are now implemented on the C++ side in libbcc. Migrate them to use the new support and remove the old Python classes.

**Comment by vmg** [comment]
Yes! That would be neat. I need to apologize because my dayjob at GitHub has been crazy this past month. I actually have a branch that does this migration -- it's about 80% there, but a bit rough on the edges.

Would anybody be interested on wrapping it up if I push the branch? I'm afraid I don't have time to work on it this month, but I think the branch would be a solid starting point.

**Comment by vmg** [comment]
Alright, my WIP changes are in this commit: https://github.com/iovisor/bcc/commit/7cec2b8fa081d70b20a59e93f042dc949ea29098

Sorry I cannot clean these up at this point. If somebody wants to grab that an run, that'd be neat. If not I'll get back to wrapping this up sometime soon. :)

**Comment by goldshtn** [comment]
This is also tracked in #698 now.

**Comment by goldshtn** [comment]
I'm closing this issue because it's taken care of by #698.
