### ISSUE TITLE
add stack traces to trace.py

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#621]
Would be useful to have a "-s" to print stack traces.

When used on user-level probes, it would only print the user stack trace. When used on kernel, it could print both.

I did do this for kprobe/uprobe in perf-tools using ftrace, which proved very useful.

https://github.com/brendangregg/perf-tools/blob/master/examples/kprobe_example.txt#L302

**Comment by goldshtn** [comment]
Oh yeah, could be very useful, instead of poking around with a debugger. I think in terms of a timeline, I would like things to happen in this order:

1) USDT support in Python
2) Add USDT support to my branch of stackcount (this is the only thing I'm blocked on)
3) Port argdist, trace, tplist to new USDT support
4) Add stack count support to trace
5) Add uprobe support to funccount and funclatency

That's my list for the next few weeks I think :) I could also move forward with 2, 4, and 5 to get unblocked and add USDT support later. What do you think?

**Comment by brendangregg** [comment]
Sounds good. I'll look at getting the (1) code we already have integrated.

**Comment by goldshtn** [comment]
@brendangregg  I think this can be closed now with @palmtenor 's PR #712. It's not the `-s` you wanted, but I think `-K` and `-U` kind of make sense too.

**Comment by brendangregg** [comment]
Yes, we can close it, thanks @palmtenor ! And if -KU gets too annoying, we can always add "-s" as an alias for "-KU".
