### ISSUE TITLE
execsnoop error

### ISSUE THREAD

**Issue by rgrinberg** [iovisor/bcc#769]
Running execsnoop gives me the following after a short duration:

```
  File "/usr/lib/python3.5/site-packages/ipdb/__main__.py", line 168, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/share/bcc/tools/execsnoop", line 19, in <module>
    from __future__ import print_function
  File "/usr/lib/python3.5/site-packages/bcc/__init__.py", line 584, in trace_fields
    pid, cpu, flags, ts = line[:ts_end].split()
ValueError: not enough values to unpack (expected 4, got 1)
```

I've looked at what `self.trace_readline(nonblocking)` returns and it's: `@stat = lstat($ARGV[0]);` Which clearly fails to split.

**Comment by markdrayton** [comment]
How is your BCC installation set up? Did you install RPMs or build from source? execsnoop used to read data via trace_fields() and would run into problems of not splitting correctly if the trace pipe contained other stuff or commands with newlines (see also #473). It's hard to say if this is the issue for sure as your stack is missing the caller of trace_fields().

Either way, it was updated to use BPF_PERF_OUTPUT instead of the trace pipe several months ago (https://github.com/iovisor/bcc/commit/5b47e0f80e42b38c09f852e46d948483cbec7594). Maybe your installation is old?

**Comment by rgrinberg** [comment]
You're right, looks like my version if `0.1.8`. I'm on Archlinux and installed it from the AUR as recommended: https://aur.archlinux.org/packages/bcc/

Will upgrade and see if I can reproduce.

**Comment by pchaigno** [comment]
@rgrinberg Were you able to reproduce with a newer version?

**Comment by goldshtn** [comment]
Closing for now, please update if this is still an issue. @rgrinberg
