### ISSUE TITLE
Is there a way to iter through any map?

### ISSUE THREAD

**Issue by vitalyvch** [iovisor/bcc#898]
I would like to collect results of fork()/vfork()/clone() end extend a list of traced processes in runtime.

Currently, I'm going to use BPF_HASH by using indexes as keys and pids as leafs, but it is good to avoid maintaining of indexes.

@marcinslusarz, @GBuella, @ldorau, @plebioda, @sarahjelinek

**Comment by pchaigno** [comment]
Because BPF disallow variable-sized loops (by disallowing backward jumps), accesses to dynamic data structures are only possible through helpers. So, as far as I know, it's not currently possible to iterate through a map. I'm guessing your current loop on `BPF_HASH` is bounded and unrolled by Clang?

To extend your list of traced processes at runtime, couldn't you save PIDs in a `BPF_HASH` map (`map.update(pid, 1)`) and then, when you need to filter traced processes, just do a lookup (`map.lookup(pid) == 1`)?

**Comment by vitalyvch** [comment]
Hmmm ... Thanks. I will think one time more.

**Comment by vitalyvch** [comment]
So idea was implemented and works excellent. Thanks.
