### ISSUE TITLE
trace: more invalid function characters from golang

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#903]
I was previously testing gccgo, now using just go:

```Shell
# ./funccount.py '/root/echotls:crypto.tls*'
Tracing 197 functions for "/root/echotls:crypto.tls*"... Hit Ctrl-C to end.
^C
FUNC                                    COUNT
crypto/tls.ecdheRSAKA                       1
crypto/tls.(*Config).ticketKeys             1
crypto/tls.(*Config).cipherSuites           1
crypto/tls.(*Config).getCertificate         1
crypto/tls.defaultCipherSuites              1
crypto/tls.(*halfConn).error                1
crypto/tls.(*Conn).sendAlertLocked          1
crypto/tls.(*Conn).sendAlert                1
crypto/tls.(*Conn).Write                    1
crypto/tls.(*Conn).Close                    1
crypto/tls.(*clientHelloMsg).marshal        1
crypto/tls.(*clientHelloMsg).unmarshal        1
crypto/tls.(*clientKeyExchangeMsg).unmarshal        1
crypto/tls.(*finishedMsg).unmarshal         1
[...]
```

Yes, @goldshtn was right, there's more. So that has "/", "(", "*" and ")". Maybe trace.py should have a list of these and encode them as ASCII hex, eg, "/" becomes "\_2f\_".

**Comment by brendangregg** [comment]
I'm now thinking we should just do: for every [!a-zA-Z0-9_], replace with '__H##__' where ## is the ASCII hex index. There's probably a clever way to do this in Python that I don't know yet.

And we should do this for other tools, argdist and stackcount.

**Comment by goldshtn** [comment]
The probe name is already guaranteed to be unique, because I tack on `self.probe_num` at the end, which is monotonically increasing. Which means it's fine to just remove all offending characters. However, it might make debugging a bit harder (if you want to be able to recognize the names in the resulting program), so I'm thinking of replacing all characters that are not valid in identifiers with `_`.

**Comment by goldshtn** [comment]
I think this should be fixed in #906. BTW, it doesn't apply to `stackcount`, because the probe name there is always `trace_count` or similar -- it doesn't include the original function name. Indeed, even in `trace` and `argdist` there's really no need for the original function name except for debugging the resulting BPF program.

**Comment by LieberBerry** [comment]
@brendangregg, @goldshtn, et. al. - thanks for the project and general advocacy you've undertaken. Linux tracing has been a tentalizing but abstruse for a long time but it's only now finally becoming approachable thanks to your efforts in providing learning materials and examples.  It makes all the difference.

Here's a Python snippet by way of a thank you... you're allowed to use a callable in lieu of a replace string. Though 906 has gone the simpler route.
```python
import re

def flubber(m):
    return "__H%02x__" % ord(m.group(1))

name = 'crypto/tls.(*Conn).Close'
re.sub('([^a-zA-Z0-9_])', flubber, name)

# returns 'crypto__H2f__tls__H2e____H28____H2a__Conn__H29____H2e__Close'
```

**Comment by brendangregg** [comment]
thanks @LieberBerry , we ended up not needing to encode the hex, but good to see the solution!
